/********************************************************************************************************
 * @file    pwm_reg.h
 *
 * @brief   This is the header file for tl322x
 *
 * @author  Driver Group
 * @date    2024
 *
 * @par     Copyright (c) 2024, Telink Semiconductor (Shanghai) Co., Ltd. ("TELINK")
 *
 *          Licensed under the Apache License, Version 2.0 (the "License");
 *          you may not use this file except in compliance with the License.
 *          You may obtain a copy of the License at
 *
 *              http://www.apache.org/licenses/LICENSE-2.0
 *
 *          Unless required by applicable law or agreed to in writing, software
 *          distributed under the License is distributed on an "AS IS" BASIS,
 *          WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *          See the License for the specific language governing permissions and
 *          limitations under the License.
 *
 *******************************************************************************************************/
#ifndef PWM_REG_H
#define PWM_REG_H

#include "soc.h"


/*******************************      pwm registers: 0x140e00      ******************************/
#define reg_pwm_data_buf_adr 0x80140e00


/**
 * Represents the base address register of the PWM
 */
#define REG_PWM_BASE 0x140e00


/**
 * PWM data fifo.0x140e00~0x140e02.
 */
#define reg_pwm_ir_fifo_dat(i)  REG_ADDR16(REG_PWM_BASE+0x00+i*2)

/**
 * [7:0] bits 7-0 of PWM0's high time or low time(if pola[0]=1),if shadow bit(fifo data[14]) is 1 in ir fifo mode or dma fifo mode.
 */
#define reg_pwm_tcmp0_shadow    REG_ADDR16(REG_PWM_BASE+0x04)


/**
 * [15:8] bits 15-8 of PWM0's high time or low time(if pola[0]=1),if shadow bit(fifo data[14]) is 1 in ir fifo mode or dma fifo mode.
 */
#define reg_pwm_tmax0_shadow    REG_ADDR16(REG_PWM_BASE+0x06)


/**
 * When PWM0 is in count mode or ir mode, the total number of pulse_number is set by the following two registers.
 */
#define reg_pwm0_pulse_num      REG_ADDR16(REG_PWM_BASE+0x0a)//0x32[7:0] 0x33[5:0]


/**
 * In count mode, each period is incremented by one.
 */
#define reg_pwm_ncnt            REG_ADDR16(REG_PWM_BASE+0x0c)


/**
 * This register is used to set the division factor of the PWM clock.
 */
#define reg_pwm_clkdiv          REG_ADDR8(REG_PWM_BASE+0x10)

/**
 * BIT[3:0] of this register is used to set the working mode of PWM0.Only PWM0 supports 5 modes.
 */
#define reg_pwm0_mode           REG_ADDR8(REG_PWM_BASE+0x11)
enum{

   /**
    * FLD_OUT2ANA_EN_O -> 1 : The Pwm0 signal is output to the chip's internal analog circuitry.
    * FLD_OUT2ANA_EN_O -> 0(default) : The Pwm0 signal is not output to the chip's internal analog circuitry.
    */
    FLD_OUT2ANA_EN_O     = BIT(4),
};

/**
 * This register BIT[3:0] indicates the interrupt trigger level in ir_fifo mode.
 * When fifo numbers is less than this value.It's will take effect.
 */
#define reg_pwm_ctrl_b2         REG_ADDR8(REG_PWM_BASE + 0x12)
enum{
     FLD_IRQ_PWM_NUM_MASK = BIT(0),
     FLD_IRQ_FIFO_MASK    = BIT(1),
     FLD_IRQ_LVL_MASK     = BIT(2),
     FLD_PWM0_FIFO_NUM_OF_TRIGGER_LEVEL  = BIT_RNG(4,7),
};

#define reg_pwm_ctrl_b3           REG_ADDR8(REG_PWM_BASE+0x13)
enum{

    FLD_RESOL_UP_MODE    = BIT(5),
    FLD_DITH_MODE        = BIT(6),
};


/**
 * This register indicates the fifo data status in.
 * BIT[3:0]:Indicates the amount of data in the FIFO.
 * BIT[4]:if BIT[4]=1,Indicates the data fifo is empty.
 * BIT[5]:if BIT[5]=1,Indicates the data fifo is full.
 */
#define reg_pwm_ir_fifo_data_status     REG_ADDR8(REG_PWM_BASE+0x14)
enum{
    FLD_PWM0_IR_FIFO_DATA_NUM   =       BIT_RNG(0,3),
    FLD_PWM0_IR_FIFO_EMPTY      =       BIT(4),
    FLD_PWM0_IR_FIFO_FULL       =       BIT(5),
};

/**
 * This register can be configured to clear the data FIFO.
 * BIT[0]:if BIT[0]=1,Indicates the data FIFO is clear.
 */
#define reg_pwm_ir_clr_fifo_data        REG_ADDR8(REG_PWM_BASE+0x15)
enum{
    FLD_PWM0_IR_FIFO_CLR_DATA   =       BIT(0),
};


/**
 * The bits in this register are used to indicate the various interrupt states of the PWM.
 * BIT[0]:This bit is usually used with BIT[0] of 0x140430. If this bit is set to 1, it means that a pulse group of PWM has been sent.An interrupt was also generated. You can manually write 1 to clear the interrupt flag.
 * BIT[1]:In ir dma fifo mode. If this is set 1 Indicates that a set of pulse of group has been sent. You can manually write 1 to clear the interrupt flag.
 * BIT[2]:When the FIFO value is less than the set value, an interrupt is generated(The premise is that this interrupt has been enabled by register 0x140432 previous).
 *        The user can know whether this interrupt is generated by reading the status of this register.If BIT(8):1 Indicates that this interrupt has been generated.
 */
#define reg_pwm_int        REG_ADDR16(REG_PWM_BASE+0x16)


/**
 * The bits in this register are used to indicate the various interrupt states of the PWM.
 * BIT[0]:This bit is usually used with BIT[0] of 0x140430. If this bit is set to 1, it means that a pulse group of PWM has been sent.An interrupt was also generated. You can manually write 1 to clear the interrupt flag.
 * BIT[1]:In ir dma fifo mode. If this is set 1 Indicates that a set of pulse of group has been sent. You can manually write 1 to clear the interrupt flag.
 * BIT[8]:When the FIFO value is less than the set value, an interrupt is generated(The premise is that this interrupt has been enabled by register 0x140432 previous).
 *        The user can know whether this interrupt is generated by reading the status of this register.If BIT(8):1 Indicates that this interrupt has been generated.
 * BIT[9]:If this is set 1 Indicates that a signal frame interrupt has been generated. You can manually write 1 to clear the interrupt flag.
 * BIT[10]:If this is set 1 Indicates that a signal frame interrupt has been generated. You can manually write 1 to clear the interrupt flag.
 * BIT[11]:If this is set 1 Indicates that a signal frame interrupt has been generated. You can manually write 1 to clear the interrupt flag.
 * BIT[12]:If this is set 1 Indicates that a signal frame interrupt has been generated. You can manually write 1 to clear the interrupt flag.
 * BIT[13]:If this is set 1 Indicates that a signal frame interrupt has been generated. You can manually write 1 to clear the interrupt flag.
 * BIT[14]:If this is set 1 Indicates that a signal frame interrupt has been generated. You can manually write 1 to clear the interrupt flag.
 * BIT[15]:If this is set 1 Indicates that a signal frame interrupt has been generated. You can manually write 1 to clear the interrupt flag.
 */
#define reg_pwm_irq_sta        REG_ADDR32(REG_PWM_BASE+0x18)
typedef enum{
    FLD_PWM0_PNUM_IRQ           =    BIT(0),    FLD_PWM0_FRAME_DONE_IRQ    =    BIT(0),
    FLD_PWM0_IR_DMA_FIFO_IRQ    =    BIT(1),    FLD_PWM1_FRAME_DONE_IRQ    =    BIT(1),
    FLD_PWM0_IR_FIFO_IRQ        =    BIT(2),    FLD_PWM2_FRAME_DONE_IRQ    =    BIT(2),
    FLD_PWM_IRQ_CYCDONE_MASK    =    BIT(6),    FLD_PWM6_FRAME_DONE_IRQ    =    BIT(6),
    FLD_PWM3_FRAME_DONE_IRQ              =      BIT(3),
    FLD_PWM4_FRAME_DONE_IRQ              =      BIT(4),
    FLD_PWM5_FRAME_DONE_IRQ              =      BIT(5),
    FLD_PWM7_FRAME_DONE_IRQ              =      BIT(7),
    FLD_PWM8_FRAME_DONE_IRQ              =      BIT(8),
    FLD_PWM9_FRAME_DONE_IRQ              =      BIT(9),
    FLD_PWM10_FRAME_DONE_IRQ              =      BIT(10),
    FLD_PWM11_FRAME_DONE_IRQ              =      BIT(11),
    FLD_PWM12_FRAME_DONE_IRQ              =      BIT(12),
    FLD_PWM13_FRAME_DONE_IRQ              =      BIT(13),
    FLD_PWM14_FRAME_DONE_IRQ              =      BIT(14),
    FLD_PWM15_FRAME_DONE_IRQ              =      BIT(15),
    FLD_PWM16_FRAME_DONE_IRQ              =      BIT(16),
    FLD_PWM17_FRAME_DONE_IRQ              =      BIT(17),
    FLD_PWM18_FRAME_DONE_IRQ              =      BIT(18),
    FLD_PWM19_FRAME_DONE_IRQ              =      BIT(19),
    FLD_PWM20_FRAME_DONE_IRQ              =      BIT(20),
    FLD_PWM21_FRAME_DONE_IRQ              =      BIT(21),
    FLD_PWM22_FRAME_DONE_IRQ              =      BIT(22),
    FLD_PWM23_FRAME_DONE_IRQ              =      BIT(23),
}pwm_irq_e;


/**
 * This register is used to enable PWM0~PWM23.
 */
#define reg_pwm_enable          REG_ADDR32(REG_PWM_BASE+0x1c)
typedef enum{
    FLD_PWM1_EN = BIT(1),
    FLD_PWM2_EN = BIT(2),
    FLD_PWM3_EN = BIT(3),
    FLD_PWM4_EN = BIT(4),
    FLD_PWM5_EN = BIT(5),
    FLD_PWM6_EN = BIT(6),
    FLD_PWM7_EN = BIT(7),

    FLD_PWM8_EN = BIT(8),
    FLD_PWM9_EN = BIT(9),
    FLD_PWM10_EN = BIT(10),
    FLD_PWM11_EN = BIT(11),
    FLD_PWM12_EN = BIT(12),
    FLD_PWM13_EN = BIT(13),
    FLD_PWM14_EN = BIT(14),
    FLD_PWM15_EN = BIT(15),

    FLD_PWM16_EN = BIT(16),
    FLD_PWM17_EN = BIT(17),
    FLD_PWM18_EN = BIT(18),
    FLD_PWM19_EN = BIT(19),
    FLD_PWM20_EN = BIT(20),
    FLD_PWM21_EN = BIT(21),
    FLD_PWM22_EN = BIT(22),
    FLD_PWM23_EN = BIT(23),

    FLD_PWM0_EN = BIT(24),
}pwm_en_e;


/**
 * This register is used to configure the period of the PWM waveform. There are 32 bits in total.
 * The lower 16 bits indicate the length of the CMP segment. The higher 16 bits indicate the length of the MAX segment.
 */
#define reg_pwm_cycle(i)        REG_ADDR32(REG_PWM_BASE+0x20 + (i * 0x10))
//enum{
//  FLD_PWM_CMP  =              BIT_RNG(0,15),
//  FLD_PWM_MAX  =              BIT_RNG(16,31),
//};
// in C99 FLD_PWM_MAX  = BIT_RNG(16,31) is error
#define FLD_PWM_CMP  =          BIT_RNG(0,15),
#define FLD_PWM_MAX  =          BIT_RNG(16,31),

/**
 * This register configures the length of the capture segment of PWM6 ~ PWM0.
 * This value has a total of 16 bits, divided into lower 8 bits and higher 8 bits.
 */
#define reg_pwm_cmp(i)          REG_ADDR16(REG_PWM_BASE+0x20 +(i * 0x10))


/**
 * This register configures the length of the max segment of PWM6 ~ PWM0.
 * This value has a total of 16 bits, divided into lower 8 bits and higher 8 bits.
 */
#define reg_pwm_max(i)          REG_ADDR16(REG_PWM_BASE+0x22 + (i * 0x10))


/**
 * this register configure pwm6~pwm0 phase
 */
#define reg_pwm_phase(i)        REG_ADDR16(REG_PWM_BASE+0x24 + (i * 0x10))


#define reg_pwm_cfg_b6(i)       REG_ADDR8(REG_PWM_BASE + 0x26 + (i * 0x10))
enum{
     FLD_PWM_OUT_INVERT         = BIT(1),
     FLD_PWM_INV_OUT_INVERT     = BIT(2),
     FLD_PWM_FIRST_OUT_LEVEL    = BIT(3),
     FLD_PWM_32K_ENABLE         = BIT(4),
     FLD_PWM_CENTER_ALIGN       = BIT(5),
};

/**
 * BIT[6:0] of this register is used to set the phase mode of PWM0-6.
 * phase_mode_o[#] ==1: phase is in every cycle.
 * phase_mode_o[#] ==0: phase is in first cycle.
 */
#define reg_pwm_cfg_b7(i)        REG_ADDR8(REG_PWM_BASE+0x27 + (i * 0x10))
enum{
    FLD_PWM_SYNC_EN              =      BIT(0),
    FLD_PWM_SYNC_EDGE            =      BIT(1),
    FLD_PWM_PHASE_MODE           =      BIT(2),
};

/**
 * this register configure pwm6~pwm0 resol.
 */
#define reg_pwm_resol(i)        REG_ADDR8(REG_PWM_BASE+0x28 + (i * 0x10))

/**
 * this register configure pwm6~pwm0 dead time.
 */
#define reg_pwm_dead(i)         REG_ADDR8(REG_PWM_BASE+0x29 + (i * 0x10))


/**
 * PWM0~PWM6, counting from 0 at the beginning of each cycle, and adding 1 for each system clock.
 */
#define reg_pwm_cnt(i)          REG_ADDR16(REG_PWM_BASE+0x2a + (i * 0x10))


#endif
