/*******************************************************************************************************
 *
 * @file    drv_gpio_ex.h
 *
 * @brief   This is the source file for tl752x
 *
 * @author  ExpanseMicro BSP Team
 * @par     Copyright (C) 2025-2035 Expanse Microelectronics (Shanghai) Co., Ltd
 *
 * @author  Telink Driver Group
 * @par     Copyright (c) 2025, Telink Semiconductor (Shanghai) Co., Ltd. ("TELINK")
 *
 * @date   2025
 *
 *          Licensed under the Apache License, Version 2.0 (the "License");
 *          you may not use this file except in compliance with the License.
 *          You may obtain a copy of the License at
 *
 *              http://www.apache.org/licenses/LICENSE-2.0
 *
 *          Unless required by applicable law or agreed to in writing, software
 *          distributed under the License is distributed on an "AS IS" BASIS,
 *          WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *          See the License for the specific language governing permissions and
 *          limitations under the License.
 *
 *******************************************************************************************************/
#ifndef __DRV_GPIO_EX_H__
#define __DRV_GPIO_EX_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "tl_chip.h"
#include "modules/drv_gpio_ex.h"

#define INPUT_MODE  0x00U
#define OUTPUT_MODE 0x01U

#define PA0_DDR  (OUTPUT_MODE << 0)
#define PA1_DDR  (OUTPUT_MODE << 1)
#define PA2_DDR  (OUTPUT_MODE << 2)
#define PA3_DDR  (OUTPUT_MODE << 3)
#define PA4_DDR  (OUTPUT_MODE << 4)
#define PA5_DDR  (OUTPUT_MODE << 5)
#define PA6_DDR  (OUTPUT_MODE << 6)
#define PA7_DDR  (OUTPUT_MODE << 7)
#define PA8_DDR  (OUTPUT_MODE << 8)
#define PA9_DDR  (OUTPUT_MODE << 9)
#define PA10_DDR (OUTPUT_MODE << 10)
#define PA11_DDR (OUTPUT_MODE << 11)
#define PA12_DDR (OUTPUT_MODE << 12)
#define PA13_DDR (OUTPUT_MODE << 13)
#define PA14_DDR (OUTPUT_MODE << 14)
#define PA15_DDR (OUTPUT_MODE << 15)
#define PA16_DDR (OUTPUT_MODE << 16)
#define PA17_DDR (OUTPUT_MODE << 17)
#define PA18_DDR (OUTPUT_MODE << 18)
#define PA19_DDR (OUTPUT_MODE << 19)
#define PA20_DDR (OUTPUT_MODE << 20)
#define PA21_DDR (OUTPUT_MODE << 21)
#define PA22_DDR (OUTPUT_MODE << 22)
#define PA23_DDR (OUTPUT_MODE << 23)
#define PA24_DDR (OUTPUT_MODE << 24)
#define PA25_DDR (OUTPUT_MODE << 25)
#define PA26_DDR (OUTPUT_MODE << 26)
#define PA27_DDR (OUTPUT_MODE << 27)
#define PA28_DDR (OUTPUT_MODE << 28)
#define PA29_DDR (OUTPUT_MODE << 29)
#define PA30_DDR (OUTPUT_MODE << 30)
#define PA31_DDR (OUTPUT_MODE << 31)

#define PB0_DDR  (OUTPUT_MODE << 0)
#define PB1_DDR  (OUTPUT_MODE << 1)
#define PB2_DDR  (OUTPUT_MODE << 2)
#define PB3_DDR  (OUTPUT_MODE << 3)
#define PB4_DDR  (OUTPUT_MODE << 4)
#define PB5_DDR  (OUTPUT_MODE << 5)
#define PB6_DDR  (OUTPUT_MODE << 6)
#define PB7_DDR  (OUTPUT_MODE << 7)
#define PB8_DDR  (OUTPUT_MODE << 8)
#define PB9_DDR  (OUTPUT_MODE << 9)
#define PB10_DDR (OUTPUT_MODE << 10)
#define PB11_DDR (OUTPUT_MODE << 11)
#define PB12_DDR (OUTPUT_MODE << 12)
#define PB13_DDR (OUTPUT_MODE << 13)

#define PC0_DDR (OUTPUT_MODE << 14)
#define PC1_DDR (OUTPUT_MODE << 15)
#define PC2_DDR (OUTPUT_MODE << 16)
#define PC3_DDR (OUTPUT_MODE << 17)
#define PC4_DDR (OUTPUT_MODE << 18)
#define PC5_DDR (OUTPUT_MODE << 19)
#define PC6_DDR (OUTPUT_MODE << 20)
#define PC7_DDR (OUTPUT_MODE << 21)
#define PC8_DDR (OUTPUT_MODE << 22)
#define PC9_DDR (OUTPUT_MODE << 23)

#define DRIVE_STRENGTH_2MA  0x00000020U /*!< 2mA */
#define DRIVE_STRENGTH_4MA  0x00000021U /*!< 4mA */
#define DRIVE_STRENGTH_8MA  0x00000022U /*!< 8mA */
#define DRIVE_STRENGTH_12MA 0x00000023U /*!< 12mA */

#define PA0_ELECTRIC  DRIVE_STRENGTH_8MA
#define PA1_ELECTRIC  DRIVE_STRENGTH_8MA
#define PA2_ELECTRIC  DRIVE_STRENGTH_8MA
#define PA3_ELECTRIC  DRIVE_STRENGTH_8MA
#define PA4_ELECTRIC  DRIVE_STRENGTH_8MA
#define PA5_ELECTRIC  DRIVE_STRENGTH_8MA
#define PA6_ELECTRIC  DRIVE_STRENGTH_8MA
#define PA7_ELECTRIC  DRIVE_STRENGTH_8MA
#define PA8_ELECTRIC  DRIVE_STRENGTH_8MA
#define PA9_ELECTRIC  DRIVE_STRENGTH_8MA
#define PA10_ELECTRIC DRIVE_STRENGTH_8MA
#define PA11_ELECTRIC DRIVE_STRENGTH_8MA
#define PA12_ELECTRIC DRIVE_STRENGTH_8MA
#define PA13_ELECTRIC DRIVE_STRENGTH_8MA
#define PA14_ELECTRIC DRIVE_STRENGTH_8MA
#define PA15_ELECTRIC DRIVE_STRENGTH_8MA
#define PA16_ELECTRIC DRIVE_STRENGTH_8MA
#define PA17_ELECTRIC DRIVE_STRENGTH_8MA
#define PA18_ELECTRIC DRIVE_STRENGTH_8MA
#define PA19_ELECTRIC DRIVE_STRENGTH_8MA
#define PA20_ELECTRIC DRIVE_STRENGTH_8MA
#define PA21_ELECTRIC DRIVE_STRENGTH_8MA
#define PA22_ELECTRIC DRIVE_STRENGTH_8MA
#define PA23_ELECTRIC DRIVE_STRENGTH_8MA
#define PA24_ELECTRIC DRIVE_STRENGTH_8MA
#define PA25_ELECTRIC DRIVE_STRENGTH_8MA
#define PA26_ELECTRIC DRIVE_STRENGTH_8MA
#define PA27_ELECTRIC DRIVE_STRENGTH_8MA
#define PA28_ELECTRIC DRIVE_STRENGTH_8MA
#define PA29_ELECTRIC DRIVE_STRENGTH_8MA
#define PA30_ELECTRIC DRIVE_STRENGTH_8MA
#define PA31_ELECTRIC DRIVE_STRENGTH_8MA

#define PB0_ELECTRIC  DRIVE_STRENGTH_8MA
#define PB1_ELECTRIC  DRIVE_STRENGTH_8MA
#define PB2_ELECTRIC  DRIVE_STRENGTH_8MA
#define PB3_ELECTRIC  DRIVE_STRENGTH_8MA
#define PB4_ELECTRIC  DRIVE_STRENGTH_8MA
#define PB5_ELECTRIC  DRIVE_STRENGTH_8MA
#define PB6_ELECTRIC  DRIVE_STRENGTH_8MA
#define PB7_ELECTRIC  DRIVE_STRENGTH_8MA
#define PB8_ELECTRIC  DRIVE_STRENGTH_8MA
#define PB9_ELECTRIC  DRIVE_STRENGTH_8MA
#define PB10_ELECTRIC DRIVE_STRENGTH_8MA
#define PB11_ELECTRIC DRIVE_STRENGTH_8MA
#define PB12_ELECTRIC DRIVE_STRENGTH_8MA
#define PB13_ELECTRIC DRIVE_STRENGTH_8MA

#define PC0_ELECTRIC DRIVE_STRENGTH_8MA
#define PC1_ELECTRIC DRIVE_STRENGTH_8MA
#define PC2_ELECTRIC DRIVE_STRENGTH_8MA
#define PC3_ELECTRIC DRIVE_STRENGTH_8MA
#define PC4_ELECTRIC DRIVE_STRENGTH_8MA
#define PC5_ELECTRIC DRIVE_STRENGTH_8MA
#define PC6_ELECTRIC DRIVE_STRENGTH_8MA
#define PC7_ELECTRIC DRIVE_STRENGTH_8MA
#define PC8_ELECTRIC DRIVE_STRENGTH_12MA
#define PC9_ELECTRIC DRIVE_STRENGTH_12MA

#define PULL_UP   0x00000028U
#define PULL_DOWN 0x00000024U
#define NO_PULL   0x00000020U
#define PA0_PULL  PULL_UP
#define PA1_PULL  PULL_UP
#define PA2_PULL  PULL_UP
#define PA3_PULL  PULL_UP
#define PA4_PULL  PULL_UP
#define PA5_PULL  PULL_UP
#define PA6_PULL  PULL_UP
#define PA7_PULL  PULL_UP
#define PA8_PULL  PULL_UP
#define PA9_PULL  PULL_DOWN
#define PA10_PULL PULL_UP
#define PA11_PULL PULL_UP
#define PA12_PULL PULL_UP
#define PA13_PULL PULL_UP
#define PA14_PULL PULL_UP
#define PA15_PULL PULL_UP
#define PA16_PULL PULL_UP
#define PA17_PULL PULL_UP
#define PA18_PULL PULL_UP
#define PA19_PULL PULL_UP
#define PA20_PULL PULL_UP
#define PA21_PULL PULL_UP
#define PA22_PULL PULL_UP
#define PA23_PULL PULL_UP
#define PA24_PULL PULL_UP
#define PA25_PULL PULL_UP
#define PA26_PULL PULL_UP
#define PA27_PULL PULL_UP
#define PA28_PULL PULL_UP
#define PA29_PULL PULL_UP
#define PA30_PULL PULL_UP
#define PA31_PULL PULL_UP
#define PB0_PULL  PULL_UP
#define PB1_PULL  PULL_UP
#define PB2_PULL  PULL_UP
#define PB3_PULL  PULL_UP
#define PB4_PULL  PULL_UP
#define PB5_PULL  PULL_UP
#define PB6_PULL  PULL_UP
#define PB7_PULL  PULL_UP
#define PB8_PULL  PULL_UP
#define PB9_PULL  PULL_UP
#define PB10_PULL PULL_UP
#define PB11_PULL PULL_UP
#define PB12_PULL PULL_UP
#define PB13_PULL PULL_UP
#define PC0_PULL  PULL_DOWN
#define PC1_PULL  PULL_UP
#define PC2_PULL  PULL_UP
#define PC3_PULL  PULL_UP
#define PC4_PULL  PULL_UP
#define PC5_PULL  PULL_UP
#define PC6_PULL  PULL_UP
#define PC7_PULL  PULL_UP
#define PC8_PULL  PULL_UP
#define PC9_PULL  NO_PULL

#define FUNC_0  0
#define FUNC_1  1
#define FUNC_2  2
#define FUNC_3  3
#define FUNC_4  4
#define FUNC_5  5
#define FUNC_6  6
#define FUNC_7  7
#define FUNC_8  8
#define FUNC_9  9
#define FUNC_10 10
#define FUNC_11 11
#define FUNC_12 12
#define FUNC_13 13
#define FUNC_14 14
#define FUNC_15 15

#define PA0_MUX_CTL  FUNC_0
#define PA1_MUX_CTL  FUNC_0
#define PA2_MUX_CTL  FUNC_0
#define PA3_MUX_CTL  FUNC_0
#define PA4_MUX_CTL  FUNC_0
#define PA5_MUX_CTL  FUNC_0
#define PA6_MUX_CTL  FUNC_0
#define PA7_MUX_CTL  FUNC_0
#define PA8_MUX_CTL  FUNC_0
#define PA9_MUX_CTL  FUNC_0
#define PA10_MUX_CTL FUNC_0
#define PA11_MUX_CTL FUNC_0
#define PA12_MUX_CTL FUNC_0
#define PA13_MUX_CTL FUNC_0
#define PA14_MUX_CTL FUNC_0
#define PA15_MUX_CTL FUNC_0
#define PA16_MUX_CTL FUNC_0
#define PA17_MUX_CTL FUNC_0
#define PA18_MUX_CTL FUNC_0
#define PA19_MUX_CTL FUNC_0
#define PA20_MUX_CTL FUNC_0
#define PA21_MUX_CTL FUNC_0
#define PA22_MUX_CTL FUNC_0
#define PA23_MUX_CTL FUNC_0
#define PA24_MUX_CTL FUNC_0
#define PA25_MUX_CTL FUNC_0
#define PA26_MUX_CTL FUNC_0
#define PA27_MUX_CTL FUNC_0
#define PA28_MUX_CTL FUNC_0
#define PA29_MUX_CTL FUNC_0
#define PA30_MUX_CTL FUNC_0
#define PA31_MUX_CTL FUNC_0

#define PB0_MUX_CTL      FUNC_0
#define PB1_MUX_CTL      FUNC_0
#define PB2_MUX_CTL      FUNC_0
#define PB3_MUX_CTL      FUNC_0
#define PB4_MUX_CTL      FUNC_0
#define PB5_MUX_CTL      FUNC_0
#define PB6_MUX_CTL      FUNC_0
#define PB7_MUX_CTL      FUNC_0
#define PB8_MUX_CTL      FUNC_0
#define PB9_MUX_CTL      FUNC_0
#define PB10_MUX_CTL     FUNC_0
#define PB11_MUX_CTL     FUNC_0
#define PB12_MUX_CTL     FUNC_0
#define PB13_MUX_CTL     FUNC_0
#define PB_SWIRE_MUX_CTL FUNC_1

#define PC0_MUX_CTL FUNC_0
#define PC1_MUX_CTL FUNC_0
#define PC2_MUX_CTL FUNC_0
#define PC3_MUX_CTL FUNC_0
#define PC4_MUX_CTL FUNC_0
#define PC5_MUX_CTL FUNC_0
#define PC6_MUX_CTL FUNC_0
#define PC7_MUX_CTL FUNC_0
#define PC8_MUX_CTL FUNC_0
#define PC9_MUX_CTL FUNC_0

#define INTR_DISABLE  0x00000000U
#define INTR_ENABLE   0x00000001U
#define PA0_INTR_CTL  (INTR_DISABLE << 0)
#define PA1_INTR_CTL  (INTR_DISABLE << 1)
#define PA2_INTR_CTL  (INTR_DISABLE << 2)
#define PA3_INTR_CTL  (INTR_DISABLE << 3)
#define PA4_INTR_CTL  (INTR_DISABLE << 4)
#define PA5_INTR_CTL  (INTR_DISABLE << 5)
#define PA6_INTR_CTL  (INTR_DISABLE << 6)
#define PA7_INTR_CTL  (INTR_DISABLE << 7)
#define PA8_INTR_CTL  (INTR_DISABLE << 8)
#define PA9_INTR_CTL  (INTR_DISABLE << 9)
#define PA10_INTR_CTL (INTR_DISABLE << 10)
#define PA11_INTR_CTL (INTR_DISABLE << 11)
#define PA12_INTR_CTL (INTR_DISABLE << 12)
#define PA13_INTR_CTL (INTR_DISABLE << 13)
#define PA14_INTR_CTL (INTR_DISABLE << 14)
#define PA15_INTR_CTL (INTR_DISABLE << 15)
#define PA16_INTR_CTL (INTR_DISABLE << 16)
#define PA17_INTR_CTL (INTR_DISABLE << 17)
#define PA18_INTR_CTL (INTR_DISABLE << 18)
#define PA19_INTR_CTL (INTR_DISABLE << 19)
#define PA20_INTR_CTL (INTR_DISABLE << 20)
#define PA21_INTR_CTL (INTR_DISABLE << 21)
#define PA22_INTR_CTL (INTR_DISABLE << 22)
#define PA23_INTR_CTL (INTR_DISABLE << 23)
#define PA24_INTR_CTL (INTR_DISABLE << 24)
#define PA25_INTR_CTL (INTR_DISABLE << 25)
#define PA26_INTR_CTL (INTR_DISABLE << 26)
#define PA27_INTR_CTL (INTR_DISABLE << 27)
#define PA28_INTR_CTL (INTR_DISABLE << 28)
#define PA29_INTR_CTL (INTR_DISABLE << 29)
#define PA30_INTR_CTL (INTR_DISABLE << 30)
#define PA31_INTR_CTL (INTR_DISABLE << 31)
#define PB0_INTR_CTL  (INTR_DISABLE << 0)
#define PB1_INTR_CTL  (INTR_DISABLE << 1)
#define PB2_INTR_CTL  (INTR_DISABLE << 2)
#define PB3_INTR_CTL  (INTR_DISABLE << 3)
#define PB4_INTR_CTL  (INTR_DISABLE << 4)
#define PB5_INTR_CTL  (INTR_DISABLE << 5)
#define PB6_INTR_CTL  (INTR_DISABLE << 6)
#define PB7_INTR_CTL  (INTR_DISABLE << 7)
#define PB8_INTR_CTL  (INTR_DISABLE << 8)
#define PB9_INTR_CTL  (INTR_DISABLE << 9)
#define PB10_INTR_CTL (INTR_DISABLE << 10)
#define PB11_INTR_CTL (INTR_DISABLE << 11)
#define PB12_INTR_CTL (INTR_DISABLE << 12)
#define PB13_INTR_CTL (INTR_DISABLE << 13)

#define INTR_RISEDGE   0x00000000U
#define INTR_FALLEDGE  0x00000001U
#define PA0_INTR_TYPE  (INTR_RISEDGE << 0)
#define PA1_INTR_TYPE  (INTR_RISEDGE << 1)
#define PA2_INTR_TYPE  (INTR_RISEDGE << 2)
#define PA3_INTR_TYPE  (INTR_RISEDGE << 3)
#define PA4_INTR_TYPE  (INTR_RISEDGE << 4)
#define PA5_INTR_TYPE  (INTR_RISEDGE << 5)
#define PA6_INTR_TYPE  (INTR_RISEDGE << 6)
#define PA7_INTR_TYPE  (INTR_RISEDGE << 7)
#define PA8_INTR_TYPE  (INTR_RISEDGE << 8)
#define PA9_INTR_TYPE  (INTR_RISEDGE << 9)
#define PA10_INTR_TYPE (INTR_RISEDGE << 10)
#define PA11_INTR_TYPE (INTR_RISEDGE << 11)
#define PA12_INTR_TYPE (INTR_RISEDGE << 12)
#define PA13_INTR_TYPE (INTR_RISEDGE << 13)
#define PA14_INTR_TYPE (INTR_RISEDGE << 14)
#define PA15_INTR_TYPE (INTR_RISEDGE << 15)
#define PA16_INTR_TYPE (INTR_RISEDGE << 16)
#define PA17_INTR_TYPE (INTR_RISEDGE << 17)
#define PA18_INTR_TYPE (INTR_RISEDGE << 18)
#define PA19_INTR_TYPE (INTR_RISEDGE << 19)
#define PA20_INTR_TYPE (INTR_RISEDGE << 20)
#define PA21_INTR_TYPE (INTR_RISEDGE << 21)
#define PA22_INTR_TYPE (INTR_RISEDGE << 22)
#define PA23_INTR_TYPE (INTR_RISEDGE << 23)
#define PA24_INTR_TYPE (INTR_RISEDGE << 24)
#define PA25_INTR_TYPE (INTR_RISEDGE << 25)
#define PA26_INTR_TYPE (INTR_RISEDGE << 26)
#define PA27_INTR_TYPE (INTR_RISEDGE << 27)
#define PA28_INTR_TYPE (INTR_RISEDGE << 28)
#define PA29_INTR_TYPE (INTR_RISEDGE << 29)
#define PA30_INTR_TYPE (INTR_RISEDGE << 30)
#define PA31_INTR_TYPE (INTR_RISEDGE << 31)
#define PB0_INTR_TYPE  (INTR_RISEDGE << 0)
#define PB1_INTR_TYPE  (INTR_RISEDGE << 1)
#define PB2_INTR_TYPE  (INTR_RISEDGE << 2)
#define PB3_INTR_TYPE  (INTR_RISEDGE << 3)
#define PB4_INTR_TYPE  (INTR_RISEDGE << 4)
#define PB5_INTR_TYPE  (INTR_RISEDGE << 5)
#define PB6_INTR_TYPE  (INTR_RISEDGE << 6)
#define PB7_INTR_TYPE  (INTR_RISEDGE << 7)
#define PB8_INTR_TYPE  (INTR_RISEDGE << 8)
#define PB9_INTR_TYPE  (INTR_RISEDGE << 9)
#define PB10_INTR_TYPE (INTR_RISEDGE << 10)
#define PB11_INTR_TYPE (INTR_RISEDGE << 11)
#define PB12_INTR_TYPE (INTR_RISEDGE << 12)
#define PB13_INTR_TYPE (INTR_RISEDGE << 13)

#define INTR_DEBOUNCE_DISABLE 0x00000001U
#define INTR_DEBOUNCE_ENABLE  0x00000000U

#define PA0_INTR_DEBOUNCE_CTL  (INTR_DEBOUNCE_DISABLE << 0)
#define PA1_INTR_DEBOUNCE_CTL  (INTR_DEBOUNCE_DISABLE << 1)
#define PA2_INTR_DEBOUNCE_CTL  (INTR_DEBOUNCE_DISABLE << 2)
#define PA3_INTR_DEBOUNCE_CTL  (INTR_DEBOUNCE_DISABLE << 3)
#define PA4_INTR_DEBOUNCE_CTL  (INTR_DEBOUNCE_DISABLE << 4)
#define PA5_INTR_DEBOUNCE_CTL  (INTR_DEBOUNCE_DISABLE << 5)
#define PA6_INTR_DEBOUNCE_CTL  (INTR_DEBOUNCE_DISABLE << 6)
#define PA7_INTR_DEBOUNCE_CTL  (INTR_DEBOUNCE_DISABLE << 7)
#define PA8_INTR_DEBOUNCE_CTL  (INTR_DEBOUNCE_DISABLE << 8)
#define PA9_INTR_DEBOUNCE_CTL  (INTR_DEBOUNCE_DISABLE << 9)
#define PA10_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 10)
#define PA11_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 11)
#define PA12_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 12)
#define PA13_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 13)
#define PA14_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 14)
#define PA15_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 15)
#define PA16_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 16)
#define PA17_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 17)
#define PA18_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 18)
#define PA19_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 19)
#define PA20_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 20)
#define PA21_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 21)
#define PA22_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 22)
#define PA23_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 23)
#define PA24_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 24)
#define PA25_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 25)
#define PA26_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 26)
#define PA27_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 27)
#define PA28_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 28)
#define PA29_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 29)
#define PA30_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 30)
#define PA31_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 31)
#define PB0_INTR_DEBOUNCE_CTL  (INTR_DEBOUNCE_DISABLE << 16)
#define PB1_INTR_DEBOUNCE_CTL  (INTR_DEBOUNCE_DISABLE << 17)
#define PB2_INTR_DEBOUNCE_CTL  (INTR_DEBOUNCE_DISABLE << 18)
#define PB3_INTR_DEBOUNCE_CTL  (INTR_DEBOUNCE_DISABLE << 19)
#define PB4_INTR_DEBOUNCE_CTL  (INTR_DEBOUNCE_DISABLE << 20)
#define PB5_INTR_DEBOUNCE_CTL  (INTR_DEBOUNCE_DISABLE << 21)
#define PB6_INTR_DEBOUNCE_CTL  (INTR_DEBOUNCE_DISABLE << 22)
#define PB7_INTR_DEBOUNCE_CTL  (INTR_DEBOUNCE_DISABLE << 23)
#define PB8_INTR_DEBOUNCE_CTL  (INTR_DEBOUNCE_DISABLE << 24)
#define PB9_INTR_DEBOUNCE_CTL  (INTR_DEBOUNCE_DISABLE << 25)
#define PB10_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 26)
#define PB11_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 27)
#define PB12_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 28)
#define PB13_INTR_DEBOUNCE_CTL (INTR_DEBOUNCE_DISABLE << 29)

extern void drv_gpio_init_ex(void);

#ifdef __cplusplus
}
#endif

#endif
