/*******************************************************************************************************
 *
 * @file    sys_ctl.h
 *
 * @brief   This is the source file for tl752x
 *
 * @author  ExpanseMicro BSP Team
 * @par     Copyright (C) 2025-2035 Expanse Microelectronics (Shanghai) Co., Ltd
 *
 * @author  Telink Driver Group
 * @par     Copyright (c) 2025, Telink Semiconductor (Shanghai) Co., Ltd. ("TELINK")
 *
 * @date   2025
 *
 *          Licensed under the Apache License, Version 2.0 (the "License");
 *          you may not use this file except in compliance with the License.
 *          You may obtain a copy of the License at
 *
 *              http://www.apache.org/licenses/LICENSE-2.0
 *
 *          Unless required by applicable law or agreed to in writing, software
 *          distributed under the License is distributed on an "AS IS" BASIS,
 *          WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *          See the License for the specific language governing permissions and
 *          limitations under the License.
 *
 *******************************************************************************************************/
#ifndef __SYS_CTL_H__
#define __SYS_CTL_H__

#include "stdint.h"

#ifdef __cplusplus
extern "C" {
#endif

//PERI_CFG_REG offsetaddress : 0x21C
//PERI_CFG_REG RegResetValue : 0xNone
#define SYS_CTL_DW_APB_SSI_M_SS_IN_N_POS  (0U)
#define SYS_CTL_DW_APB_SSI_M_SS_IN_N_MSK  (0x1UL << SYS_CTL_DW_APB_SSI_M_SS_IN_N_POS) /*!< */
#define SYS_CTL_DW_APB_SSI_M_SS_IN_N      SYS_CTL_DW_APB_SSI_M_SS_IN_N_MSK
#define SYS_CTL_DW_APB_SSI_M_SS_IN_N_W(X) ((X) << SYS_CTL_DW_APB_SSI_M_SS_IN_N_POS)
#define SYS_CTL_PORT_UART1_IRDA_SEL_POS   (1U)
#define SYS_CTL_PORT_UART1_IRDA_SEL_MSK   (0x1UL << SYS_CTL_PORT_UART1_IRDA_SEL_POS) /*!< */
#define SYS_CTL_PORT_UART1_IRDA_SEL       SYS_CTL_PORT_UART1_IRDA_SEL_MSK
#define SYS_CTL_PORT_UART1_IRDA_SEL_W(X)  ((X) << SYS_CTL_PORT_UART1_IRDA_SEL_POS)
#define SYS_CTL_PORT_UART2_IRDA_SEL_POS   (2U)
#define SYS_CTL_PORT_UART2_IRDA_SEL_MSK   (0x1UL << SYS_CTL_PORT_UART2_IRDA_SEL_POS) /*!< */
#define SYS_CTL_PORT_UART2_IRDA_SEL       SYS_CTL_PORT_UART2_IRDA_SEL_MSK
#define SYS_CTL_PORT_UART2_IRDA_SEL_W(X)  ((X) << SYS_CTL_PORT_UART2_IRDA_SEL_POS)
#define SYS_CTL_PORT_UART3_IRDA_SEL_POS   (3U)
#define SYS_CTL_PORT_UART3_IRDA_SEL_MSK   (0x1UL << SYS_CTL_PORT_UART3_IRDA_SEL_POS) /*!< */
#define SYS_CTL_PORT_UART3_IRDA_SEL       SYS_CTL_PORT_UART3_IRDA_SEL_MSK
#define SYS_CTL_PORT_UART3_IRDA_SEL_W(X)  ((X) << SYS_CTL_PORT_UART3_IRDA_SEL_POS)
#define SYS_CTL_TIMER_PAUSE_POS           (5U)
#define SYS_CTL_TIMER_PAUSE_MSK           (0xffUL << SYS_CTL_TIMER_PAUSE_POS) /*!< */
#define SYS_CTL_TIMER_PAUSE               SYS_CTL_TIMER_PAUSE_MSK
#define SYS_CTL_TIMER_PAUSE_W(X)          ((X) << SYS_CTL_TIMER_PAUSE_POS)
#define SYS_CTL_I2S_MONO_EN_POS           (16U)
#define SYS_CTL_I2S_MONO_EN_MSK           (0xffUL << SYS_CTL_I2S_MONO_EN_POS) /*!< */
#define SYS_CTL_I2S_MONO_EN               SYS_CTL_I2S_MONO_EN_MSK
#define SYS_CTL_I2S_MONO_EN_W(X)          ((X) << SYS_CTL_I2S_MONO_EN_POS)
#define SYS_CTL_I2S_WORK_CO_POS           (24U)
#define SYS_CTL_I2S_WORK_CO_MSK           (0x3fUL << SYS_CTL_I2S_WORK_CO_POS) /*!< */
#define SYS_CTL_I2S_WORK_CO               SYS_CTL_I2S_WORK_CO_MSK
#define SYS_CTL_I2S_WORK_CO_W(X)          ((X) << SYS_CTL_I2S_WORK_CO_POS)

//SSI_CFG_REG offsetaddress : 0x220
//SSI_CFG_REG RegResetValue : 0xNone
#define SYS_CTL_DWC_SSI_1_SS_IN_N_POS      (0U)
#define SYS_CTL_DWC_SSI_1_SS_IN_N_MSK      (0x1UL << SYS_CTL_DWC_SSI_1_SS_IN_N_POS) /*!< */
#define SYS_CTL_DWC_SSI_1_SS_IN_N          SYS_CTL_DWC_SSI_1_SS_IN_N_MSK
#define SYS_CTL_DWC_SSI_1_SS_IN_N_W(X)     ((X) << SYS_CTL_DWC_SSI_1_SS_IN_N_POS)
#define SYS_CTL_DWC_SSI_0_SS_IN_N_POS      (1U)
#define SYS_CTL_DWC_SSI_0_SS_IN_N_MSK      (0x1UL << SYS_CTL_DWC_SSI_0_SS_IN_N_POS) /*!< */
#define SYS_CTL_DWC_SSI_0_SS_IN_N          SYS_CTL_DWC_SSI_0_SS_IN_N_MSK
#define SYS_CTL_DWC_SSI_0_SS_IN_N_W(X)     ((X) << SYS_CTL_DWC_SSI_0_SS_IN_N_POS)
#define SYS_CTL_DWC_SSI_1_XIP_DISABLE_POS  (2U)
#define SYS_CTL_DWC_SSI_1_XIP_DISABLE_MSK  (0x1UL << SYS_CTL_DWC_SSI_1_XIP_DISABLE_POS) /*!< */
#define SYS_CTL_DWC_SSI_1_XIP_DISABLE      SYS_CTL_DWC_SSI_1_XIP_DISABLE_MSK
#define SYS_CTL_DWC_SSI_1_XIP_DISABLE_W(X) ((X) << SYS_CTL_DWC_SSI_1_XIP_DISABLE_POS)
#define SYS_CTL_DWC_SSI_0_XIP_DISABLE_POS  (3U)
#define SYS_CTL_DWC_SSI_0_XIP_DISABLE_MSK  (0x1UL << SYS_CTL_DWC_SSI_0_XIP_DISABLE_POS) /*!< */
#define SYS_CTL_DWC_SSI_0_XIP_DISABLE      SYS_CTL_DWC_SSI_0_XIP_DISABLE_MSK
#define SYS_CTL_DWC_SSI_0_XIP_DISABLE_W(X) ((X) << SYS_CTL_DWC_SSI_0_XIP_DISABLE_POS)
#define SYS_CTL_DWC_SSI_1_XIP_EN_POS       (4U)
#define SYS_CTL_DWC_SSI_1_XIP_EN_MSK       (0x1UL << SYS_CTL_DWC_SSI_1_XIP_EN_POS) /*!< */
#define SYS_CTL_DWC_SSI_1_XIP_EN           SYS_CTL_DWC_SSI_1_XIP_EN_MSK
#define SYS_CTL_DWC_SSI_1_XIP_EN_W(X)      ((X) << SYS_CTL_DWC_SSI_1_XIP_EN_POS)
#define SYS_CTL_DWC_SSI_0_XIP_EN_POS       (5U)
#define SYS_CTL_DWC_SSI_0_XIP_EN_MSK       (0x1UL << SYS_CTL_DWC_SSI_0_XIP_EN_POS) /*!< */
#define SYS_CTL_DWC_SSI_0_XIP_EN           SYS_CTL_DWC_SSI_0_XIP_EN_MSK
#define SYS_CTL_DWC_SSI_0_XIP_EN_W(X)      ((X) << SYS_CTL_DWC_SSI_0_XIP_EN_POS)

//OSR_CFG_REG offsetaddress : 0x23c
//OSR_CFG_REG RegResetValue : 0xNone
#define SYS_CTL_OSR_TRNG_ALARM_POS           (0U)
#define SYS_CTL_OSR_TRNG_ALARM_MSK           (0x1UL << SYS_CTL_OSR_TRNG_ALARM_POS) /*!< */
#define SYS_CTL_OSR_TRNG_ALARM               SYS_CTL_OSR_TRNG_ALARM_MSK
#define SYS_CTL_OSR_TRNG_ALARM_W(X)          ((X) << SYS_CTL_OSR_TRNG_ALARM_POS)
#define SYS_CTL_OSR_TRNG_TRNG_RDY_POS        (1U)
#define SYS_CTL_OSR_TRNG_TRNG_RDY_MSK        (0x1UL << SYS_CTL_OSR_TRNG_TRNG_RDY_POS) /*!< */
#define SYS_CTL_OSR_TRNG_TRNG_RDY            SYS_CTL_OSR_TRNG_TRNG_RDY_MSK
#define SYS_CTL_OSR_TRNG_TRNG_RDY_W(X)       ((X) << SYS_CTL_OSR_TRNG_TRNG_RDY_POS)
#define SYS_CTL_OSR_TRNG_ENDIAN_POS          (2U)
#define SYS_CTL_OSR_TRNG_ENDIAN_MSK          (0x1UL << SYS_CTL_OSR_TRNG_ENDIAN_POS) /*!< */
#define SYS_CTL_OSR_TRNG_ENDIAN              SYS_CTL_OSR_TRNG_ENDIAN_MSK
#define SYS_CTL_OSR_TRNG_ENDIAN_W(X)         ((X) << SYS_CTL_OSR_TRNG_ENDIAN_POS)
#define SYS_CTL_OSR_SKE_AXI_ENDIAN_POS       (3U)
#define SYS_CTL_OSR_SKE_AXI_ENDIAN_MSK       (0x1UL << SYS_CTL_OSR_SKE_AXI_ENDIAN_POS) /*!< */
#define SYS_CTL_OSR_SKE_AXI_ENDIAN           SYS_CTL_OSR_SKE_AXI_ENDIAN_MSK
#define SYS_CTL_OSR_SKE_AXI_ENDIAN_W(X)      ((X) << SYS_CTL_OSR_SKE_AXI_ENDIAN_POS)
#define SYS_CTL_OSR_SKE_AHB_ENDIAN_POS       (4U)
#define SYS_CTL_OSR_SKE_AHB_ENDIAN_MSK       (0x1UL << SYS_CTL_OSR_SKE_AHB_ENDIAN_POS) /*!< */
#define SYS_CTL_OSR_SKE_AHB_ENDIAN           SYS_CTL_OSR_SKE_AHB_ENDIAN_MSK
#define SYS_CTL_OSR_SKE_AHB_ENDIAN_W(X)      ((X) << SYS_CTL_OSR_SKE_AHB_ENDIAN_POS)
#define SYS_CTL_OSR_PKE_ENDIAN_POS           (5U)
#define SYS_CTL_OSR_PKE_ENDIAN_MSK           (0x1UL << SYS_CTL_OSR_PKE_ENDIAN_POS) /*!< */
#define SYS_CTL_OSR_PKE_ENDIAN               SYS_CTL_OSR_PKE_ENDIAN_MSK
#define SYS_CTL_OSR_PKE_ENDIAN_W(X)          ((X) << SYS_CTL_OSR_PKE_ENDIAN_POS)
#define SYS_CTL_OSR_HASH_AXI_ENDIAN_POS      (6U)
#define SYS_CTL_OSR_HASH_AXI_ENDIAN_MSK      (0x1UL << SYS_CTL_OSR_HASH_AXI_ENDIAN_POS) /*!< */
#define SYS_CTL_OSR_HASH_AXI_ENDIAN          SYS_CTL_OSR_HASH_AXI_ENDIAN_MSK
#define SYS_CTL_OSR_HASH_AXI_ENDIAN_W(X)     ((X) << SYS_CTL_OSR_HASH_AXI_ENDIAN_POS)
#define SYS_CTL_OSR_HASH_AHB_ENDIAN_POS      (7U)
#define SYS_CTL_OSR_HASH_AHB_ENDIAN_MSK      (0x1UL << SYS_CTL_OSR_HASH_AHB_ENDIAN_POS) /*!< */
#define SYS_CTL_OSR_HASH_AHB_ENDIAN          SYS_CTL_OSR_HASH_AHB_ENDIAN_MSK
#define SYS_CTL_OSR_HASH_AHB_ENDIAN_W(X)     ((X) << SYS_CTL_OSR_HASH_AHB_ENDIAN_POS)
#define SYS_CTL_OSR_SKE_HREADYOUT_EN_POS     (8U)
#define SYS_CTL_OSR_SKE_HREADYOUT_EN_MSK     (0x1UL << SYS_CTL_OSR_SKE_HREADYOUT_EN_POS) /*!< */
#define SYS_CTL_OSR_SKE_HREADYOUT_EN         SYS_CTL_OSR_SKE_HREADYOUT_EN_MSK
#define SYS_CTL_OSR_SKE_HREADYOUT_EN_W(X)    ((X) << SYS_CTL_OSR_SKE_HREADYOUT_EN_POS)
#define SYS_CTL_OSR_HASH_HREADYOUT_EN_POS    (9U)
#define SYS_CTL_OSR_HASH_HREADYOUT_EN_MSK    (0x1UL << SYS_CTL_OSR_HASH_HREADYOUT_EN_POS) /*!< */
#define SYS_CTL_OSR_HASH_HREADYOUT_EN        SYS_CTL_OSR_HASH_HREADYOUT_EN_MSK
#define SYS_CTL_OSR_HASH_HREADYOUT_EN_W(X)   ((X) << SYS_CTL_OSR_HASH_HREADYOUT_EN_POS)
#define SYS_CTL_OSR_TRNG_HREADYOUT_EN_POS    (10U)
#define SYS_CTL_OSR_TRNG_HREADYOUT_EN_MSK    (0x1UL << SYS_CTL_OSR_TRNG_HREADYOUT_EN_POS) /*!< */
#define SYS_CTL_OSR_TRNG_HREADYOUT_EN        SYS_CTL_OSR_TRNG_HREADYOUT_EN_MSK
#define SYS_CTL_OSR_TRNG_HREADYOUT_EN_W(X)   ((X) << SYS_CTL_OSR_TRNG_HREADYOUT_EN_POS)
#define SYS_CTL_OSR_PKE_HREADYOUT_EN_POS     (11U)
#define SYS_CTL_OSR_PKE_HREADYOUT_EN_MSK     (0x1UL << SYS_CTL_OSR_PKE_HREADYOUT_EN_POS) /*!< */
#define SYS_CTL_OSR_PKE_HREADYOUT_EN         SYS_CTL_OSR_PKE_HREADYOUT_EN_MSK
#define SYS_CTL_OSR_PKE_HREADYOUT_EN_W(X)    ((X) << SYS_CTL_OSR_PKE_HREADYOUT_EN_POS)
#define SYS_CTL_SPACC_ENDIAN_POS             (12U)
#define SYS_CTL_SPACC_ENDIAN_MSK             (0x1UL << SYS_CTL_SPACC_ENDIAN_POS) /*!< */
#define SYS_CTL_SPACC_ENDIAN                 SYS_CTL_SPACC_ENDIAN_MSK
#define SYS_CTL_SPACC_ENDIAN_W(X)            ((X) << SYS_CTL_SPACC_ENDIAN_POS)
#define SYS_CTL_OSR_TRNG_SCLK_SEL_R_POS      (13U)
#define SYS_CTL_OSR_TRNG_SCLK_SEL_R_MSK      (0x1UL << SYS_CTL_OSR_TRNG_SCLK_SEL_R_POS) /*!< */
#define SYS_CTL_OSR_TRNG_SCLK_SEL_R          SYS_CTL_OSR_TRNG_SCLK_SEL_R_MSK
#define SYS_CTL_OSR_TRNG_SCLK_SEL_R_W(X)     ((X) << SYS_CTL_OSR_TRNG_SCLK_SEL_R_POS)
#define SYS_CTL_OSR_TRNG_SKIP_STARTUP_R_POS  (14U)
#define SYS_CTL_OSR_TRNG_SKIP_STARTUP_R_MSK  (0x1UL << SYS_CTL_OSR_TRNG_SKIP_STARTUP_R_POS) /*!< */
#define SYS_CTL_OSR_TRNG_SKIP_STARTUP_R      SYS_CTL_OSR_TRNG_SKIP_STARTUP_R_MSK
#define SYS_CTL_OSR_TRNG_SKIP_STARTUP_R_W(X) ((X) << SYS_CTL_OSR_TRNG_SKIP_STARTUP_R_POS)
#define SYS_CTL_OSR_TRNG_BYPASS_ES_R_POS     (15U)
#define SYS_CTL_OSR_TRNG_BYPASS_ES_R_MSK     (0x1UL << SYS_CTL_OSR_TRNG_BYPASS_ES_R_POS) /*!< */
#define SYS_CTL_OSR_TRNG_BYPASS_ES_R         SYS_CTL_OSR_TRNG_BYPASS_ES_R_MSK
#define SYS_CTL_OSR_TRNG_BYPASS_ES_R_W(X)    ((X) << SYS_CTL_OSR_TRNG_BYPASS_ES_R_POS)

//PDM_CFG offsetaddress : 0x254
//PDM_CFG RegResetValue : 0xNone
#define SYS_CTL_PDM1_WORKTHROUGH_POS  (0U)
#define SYS_CTL_PDM1_WORKTHROUGH_MSK  (0x1UL << SYS_CTL_PDM1_WORKTHROUGH_POS) /*!< */
#define SYS_CTL_PDM1_WORKTHROUGH      SYS_CTL_PDM1_WORKTHROUGH_MSK
#define SYS_CTL_PDM1_WORKTHROUGH_W(X) ((X) << SYS_CTL_PDM1_WORKTHROUGH_POS)

//TEST_CFG offsetaddress : 0x258
//TEST_CFG RegResetValue : 0xNone
#define SYS_CTL_TEST_SWITCH_POS   (0U)
#define SYS_CTL_TEST_SWITCH_MSK   (0x1UL << SYS_CTL_TEST_SWITCH_POS) /*!< */
#define SYS_CTL_TEST_SWITCH       SYS_CTL_TEST_SWITCH_MSK
#define SYS_CTL_TEST_SWITCH_W(X)  ((X) << SYS_CTL_TEST_SWITCH_POS)
#define SYS_CTL_TEST_CLK_SEL_POS  (1U)
#define SYS_CTL_TEST_CLK_SEL_MSK  (0x3UL << SYS_CTL_TEST_CLK_SEL_POS) /*!< */
#define SYS_CTL_TEST_CLK_SEL      SYS_CTL_TEST_CLK_SEL_MSK
#define SYS_CTL_TEST_CLK_SEL_W(X) ((X) << SYS_CTL_TEST_CLK_SEL_POS)
#define SYS_CTL_TEST_CTRL_POS     (6U)
#define SYS_CTL_TEST_CTRL_MSK     (0x3fUL << SYS_CTL_TEST_CTRL_POS) /*!< */
#define SYS_CTL_TEST_CTRL         SYS_CTL_TEST_CTRL_MSK
#define SYS_CTL_TEST_CTRL_W(X)    ((X) << SYS_CTL_TEST_CTRL_POS)

//GP_ADC offsetaddress : 0x260
//GP_ADC RegResetValue : 0xNone
#define SYS_CTL_GP_ADC_Q_1R_POS  (0U)
#define SYS_CTL_GP_ADC_Q_1R_MSK  (0xfffUL << SYS_CTL_GP_ADC_Q_1R_POS) /*!< */
#define SYS_CTL_GP_ADC_Q_1R      SYS_CTL_GP_ADC_Q_1R_MSK
#define SYS_CTL_GP_ADC_Q_1R_W(X) ((X) << SYS_CTL_GP_ADC_Q_1R_POS)
#define SYS_CTL_ENP_GP_ADC_POS   (12U)
#define SYS_CTL_ENP_GP_ADC_MSK   (0x1UL << SYS_CTL_ENP_GP_ADC_POS) /*!< */
#define SYS_CTL_ENP_GP_ADC       SYS_CTL_ENP_GP_ADC_MSK
#define SYS_CTL_ENP_GP_ADC_W(X)  ((X) << SYS_CTL_ENP_GP_ADC_POS)

//BOOT_STATUS offsetaddress : 0x264
//BOOT_STATUS RegResetValue : 0xNone
#define SYS_CTL_BOOT_STAT_POS  (0U)
#define SYS_CTL_BOOT_STAT_MSK  (0xffffffffUL << SYS_CTL_BOOT_STAT_POS) /*!< */
#define SYS_CTL_BOOT_STAT      SYS_CTL_BOOT_STAT_MSK
#define SYS_CTL_BOOT_STAT_W(X) ((X) << SYS_CTL_BOOT_STAT_POS)

//USB_ROREG_0 offsetaddress : 0x268
//USB_ROREG_0 RegResetValue : 0xNone
#define SYS_CTL_USB_ROREG_31_0_POS  (0U)
#define SYS_CTL_USB_ROREG_31_0_MSK  (0xffffffffUL << SYS_CTL_USB_ROREG_31_0_POS) /*!< */
#define SYS_CTL_USB_ROREG_31_0      SYS_CTL_USB_ROREG_31_0_MSK
#define SYS_CTL_USB_ROREG_31_0_W(X) ((X) << SYS_CTL_USB_ROREG_31_0_POS)

//USB_ROREG_1 offsetaddress : 0x26C
//USB_ROREG_1 RegResetValue : 0xNone
#define SYS_CTL_USB_ROREG_63_32_POS  (0U)
#define SYS_CTL_USB_ROREG_63_32_MSK  (0xffffffffUL << SYS_CTL_USB_ROREG_63_32_POS) /*!< */
#define SYS_CTL_USB_ROREG_63_32      SYS_CTL_USB_ROREG_63_32_MSK
#define SYS_CTL_USB_ROREG_63_32_W(X) ((X) << SYS_CTL_USB_ROREG_63_32_POS)

//USB_ROREG_2 offsetaddress : 0x270
//USB_ROREG_2 RegResetValue : 0xNone
#define SYS_CTL_USB_ROREG_95_64_POS  (0U)
#define SYS_CTL_USB_ROREG_95_64_MSK  (0xffffffffUL << SYS_CTL_USB_ROREG_95_64_POS) /*!< */
#define SYS_CTL_USB_ROREG_95_64      SYS_CTL_USB_ROREG_95_64_MSK
#define SYS_CTL_USB_ROREG_95_64_W(X) ((X) << SYS_CTL_USB_ROREG_95_64_POS)

//USB_ROREG_3 offsetaddress : 0x274
//USB_ROREG_3 RegResetValue : 0xNone
#define SYS_CTL_USB_ROREG_127_96_POS  (0U)
#define SYS_CTL_USB_ROREG_127_96_MSK  (0xffffffffUL << SYS_CTL_USB_ROREG_127_96_POS) /*!< */
#define SYS_CTL_USB_ROREG_127_96      SYS_CTL_USB_ROREG_127_96_MSK
#define SYS_CTL_USB_ROREG_127_96_W(X) ((X) << SYS_CTL_USB_ROREG_127_96_POS)

//USB_ROREG_4 offsetaddress : 0x278
//USB_ROREG_4 RegResetValue : 0xNone
#define SYS_CTL_USB_ROREG_159_128_POS  (0U)
#define SYS_CTL_USB_ROREG_159_128_MSK  (0xffffffffUL << SYS_CTL_USB_ROREG_159_128_POS) /*!< */
#define SYS_CTL_USB_ROREG_159_128      SYS_CTL_USB_ROREG_159_128_MSK
#define SYS_CTL_USB_ROREG_159_128_W(X) ((X) << SYS_CTL_USB_ROREG_159_128_POS)

//USB_ROREG_5 offsetaddress : 0x27C
//USB_ROREG_5 RegResetValue : 0xNone
#define SYS_CTL_USB_ROREG_191_160_POS  (0U)
#define SYS_CTL_USB_ROREG_191_160_MSK  (0xffffffffUL << SYS_CTL_USB_ROREG_191_160_POS) /*!< */
#define SYS_CTL_USB_ROREG_191_160      SYS_CTL_USB_ROREG_191_160_MSK
#define SYS_CTL_USB_ROREG_191_160_W(X) ((X) << SYS_CTL_USB_ROREG_191_160_POS)

//USB_ROREG_6 offsetaddress : 0x280
//USB_ROREG_6 RegResetValue : 0xNone
#define SYS_CTL_USB_ROREG_223_192_POS  (0U)
#define SYS_CTL_USB_ROREG_223_192_MSK  (0xffffffffUL << SYS_CTL_USB_ROREG_223_192_POS) /*!< */
#define SYS_CTL_USB_ROREG_223_192      SYS_CTL_USB_ROREG_223_192_MSK
#define SYS_CTL_USB_ROREG_223_192_W(X) ((X) << SYS_CTL_USB_ROREG_223_192_POS)

//USB_ROREG_7 offsetaddress : 0x284
//USB_ROREG_7 RegResetValue : 0xNone
#define SYS_CTL_USB_ROREG_255_224_POS  (0U)
#define SYS_CTL_USB_ROREG_255_224_MSK  (0xffffffffUL << SYS_CTL_USB_ROREG_255_224_POS) /*!< */
#define SYS_CTL_USB_ROREG_255_224      SYS_CTL_USB_ROREG_255_224_MSK
#define SYS_CTL_USB_ROREG_255_224_W(X) ((X) << SYS_CTL_USB_ROREG_255_224_POS)

//USB_ROREG_8 offsetaddress : 0x288
//USB_ROREG_8 RegResetValue : 0xNone
#define SYS_CTL_USB_ROREG_287_256_POS  (0U)
#define SYS_CTL_USB_ROREG_287_256_MSK  (0xffffffffUL << SYS_CTL_USB_ROREG_287_256_POS) /*!< */
#define SYS_CTL_USB_ROREG_287_256      SYS_CTL_USB_ROREG_287_256_MSK
#define SYS_CTL_USB_ROREG_287_256_W(X) ((X) << SYS_CTL_USB_ROREG_287_256_POS)

//USB_ROREG_9 offsetaddress : 0x28C
//USB_ROREG_9 RegResetValue : 0xNone
#define SYS_CTL_USB_ROREG_319_288_POS  (0U)
#define SYS_CTL_USB_ROREG_319_288_MSK  (0xffffffffUL << SYS_CTL_USB_ROREG_319_288_POS) /*!< */
#define SYS_CTL_USB_ROREG_319_288      SYS_CTL_USB_ROREG_319_288_MSK
#define SYS_CTL_USB_ROREG_319_288_W(X) ((X) << SYS_CTL_USB_ROREG_319_288_POS)

//USB_RWREG_0 offsetaddress : 0x290
//USB_RWREG_0 RegResetValue : 0xNone
#define SYS_CTL_USB_RWREG_31_0_POS  (0U)
#define SYS_CTL_USB_RWREG_31_0_MSK  (0xffffffffUL << SYS_CTL_USB_RWREG_31_0_POS) /*!< */
#define SYS_CTL_USB_RWREG_31_0      SYS_CTL_USB_RWREG_31_0_MSK
#define SYS_CTL_USB_RWREG_31_0_W(X) ((X) << SYS_CTL_USB_RWREG_31_0_POS)

//USB_RWREG_1 offsetaddress : 0x294
//USB_RWREG_1 RegResetValue : 0xNone
#define SYS_CTL_USB_RWREG_63_32_POS  (0U)
#define SYS_CTL_USB_RWREG_63_32_MSK  (0xffffffffUL << SYS_CTL_USB_RWREG_63_32_POS) /*!< */
#define SYS_CTL_USB_RWREG_63_32      SYS_CTL_USB_RWREG_63_32_MSK
#define SYS_CTL_USB_RWREG_63_32_W(X) ((X) << SYS_CTL_USB_RWREG_63_32_POS)

//USB_RWREG_2 offsetaddress : 0x298
//USB_RWREG_2 RegResetValue : 0xNone
#define SYS_CTL_USB_RWREG_95_64_POS  (0U)
#define SYS_CTL_USB_RWREG_95_64_MSK  (0xffffffffUL << SYS_CTL_USB_RWREG_95_64_POS) /*!< */
#define SYS_CTL_USB_RWREG_95_64      SYS_CTL_USB_RWREG_95_64_MSK
#define SYS_CTL_USB_RWREG_95_64_W(X) ((X) << SYS_CTL_USB_RWREG_95_64_POS)

//USB_RWREG_3 offsetaddress : 0x29C
//USB_RWREG_3 RegResetValue : 0xNone
#define SYS_CTL_USB_RWREG_127_96_POS  (0U)
#define SYS_CTL_USB_RWREG_127_96_MSK  (0xffffffffUL << SYS_CTL_USB_RWREG_127_96_POS) /*!< */
#define SYS_CTL_USB_RWREG_127_96      SYS_CTL_USB_RWREG_127_96_MSK
#define SYS_CTL_USB_RWREG_127_96_W(X) ((X) << SYS_CTL_USB_RWREG_127_96_POS)

//AUDIO_FUNC_DMA_SEL offsetaddress : 0x2D0
//AUDIO_FUNC_DMA_SEL RegResetValue : 0xNone
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_0_POS   (0U)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_0_MSK   (0x1UL << SYS_CTL_AUDIO_FUNC_DMA_SEL_0_POS) /*!< */
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_0       SYS_CTL_AUDIO_FUNC_DMA_SEL_0_MSK
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_0_W(X)  ((X) << SYS_CTL_AUDIO_FUNC_DMA_SEL_0_POS)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_1_POS   (1U)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_1_MSK   (0x1UL << SYS_CTL_AUDIO_FUNC_DMA_SEL_1_POS) /*!< */
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_1       SYS_CTL_AUDIO_FUNC_DMA_SEL_1_MSK
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_1_W(X)  ((X) << SYS_CTL_AUDIO_FUNC_DMA_SEL_1_POS)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_2_POS   (2U)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_2_MSK   (0x1UL << SYS_CTL_AUDIO_FUNC_DMA_SEL_2_POS) /*!< */
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_2       SYS_CTL_AUDIO_FUNC_DMA_SEL_2_MSK
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_2_W(X)  ((X) << SYS_CTL_AUDIO_FUNC_DMA_SEL_2_POS)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_3_POS   (3U)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_3_MSK   (0x1UL << SYS_CTL_AUDIO_FUNC_DMA_SEL_3_POS) /*!< */
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_3       SYS_CTL_AUDIO_FUNC_DMA_SEL_3_MSK
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_3_W(X)  ((X) << SYS_CTL_AUDIO_FUNC_DMA_SEL_3_POS)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_4_POS   (4U)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_4_MSK   (0x1UL << SYS_CTL_AUDIO_FUNC_DMA_SEL_4_POS) /*!< */
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_4       SYS_CTL_AUDIO_FUNC_DMA_SEL_4_MSK
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_4_W(X)  ((X) << SYS_CTL_AUDIO_FUNC_DMA_SEL_4_POS)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_5_POS   (5U)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_5_MSK   (0x1UL << SYS_CTL_AUDIO_FUNC_DMA_SEL_5_POS) /*!< */
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_5       SYS_CTL_AUDIO_FUNC_DMA_SEL_5_MSK
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_5_W(X)  ((X) << SYS_CTL_AUDIO_FUNC_DMA_SEL_5_POS)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_6_POS   (6U)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_6_MSK   (0x1UL << SYS_CTL_AUDIO_FUNC_DMA_SEL_6_POS) /*!< */
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_6       SYS_CTL_AUDIO_FUNC_DMA_SEL_6_MSK
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_6_W(X)  ((X) << SYS_CTL_AUDIO_FUNC_DMA_SEL_6_POS)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_7_POS   (7U)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_7_MSK   (0x1UL << SYS_CTL_AUDIO_FUNC_DMA_SEL_7_POS) /*!< */
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_7       SYS_CTL_AUDIO_FUNC_DMA_SEL_7_MSK
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_7_W(X)  ((X) << SYS_CTL_AUDIO_FUNC_DMA_SEL_7_POS)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_8_POS   (8U)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_8_MSK   (0x1UL << SYS_CTL_AUDIO_FUNC_DMA_SEL_8_POS) /*!< */
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_8       SYS_CTL_AUDIO_FUNC_DMA_SEL_8_MSK
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_8_W(X)  ((X) << SYS_CTL_AUDIO_FUNC_DMA_SEL_8_POS)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_9_POS   (9U)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_9_MSK   (0x1UL << SYS_CTL_AUDIO_FUNC_DMA_SEL_9_POS) /*!< */
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_9       SYS_CTL_AUDIO_FUNC_DMA_SEL_9_MSK
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_9_W(X)  ((X) << SYS_CTL_AUDIO_FUNC_DMA_SEL_9_POS)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_10_POS  (10U)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_10_MSK  (0x1UL << SYS_CTL_AUDIO_FUNC_DMA_SEL_10_POS) /*!< */
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_10      SYS_CTL_AUDIO_FUNC_DMA_SEL_10_MSK
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_10_W(X) ((X) << SYS_CTL_AUDIO_FUNC_DMA_SEL_10_POS)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_11_POS  (11U)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_11_MSK  (0x1UL << SYS_CTL_AUDIO_FUNC_DMA_SEL_11_POS) /*!< */
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_11      SYS_CTL_AUDIO_FUNC_DMA_SEL_11_MSK
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_11_W(X) ((X) << SYS_CTL_AUDIO_FUNC_DMA_SEL_11_POS)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_12_POS  (12U)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_12_MSK  (0x1UL << SYS_CTL_AUDIO_FUNC_DMA_SEL_12_POS) /*!< */
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_12      SYS_CTL_AUDIO_FUNC_DMA_SEL_12_MSK
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_12_W(X) ((X) << SYS_CTL_AUDIO_FUNC_DMA_SEL_12_POS)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_13_POS  (13U)
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_13_MSK  (0x1UL << SYS_CTL_AUDIO_FUNC_DMA_SEL_13_POS) /*!< */
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_13      SYS_CTL_AUDIO_FUNC_DMA_SEL_13_MSK
#define SYS_CTL_AUDIO_FUNC_DMA_SEL_13_W(X) ((X) << SYS_CTL_AUDIO_FUNC_DMA_SEL_13_POS)

//DLL_RXDS offsetaddress : 0x2E0
//DLL_RXDS RegResetValue : 0xNone
#define SYS_CTL_DLL_RXDS_DELAY_NUM_POS    (0U)
#define SYS_CTL_DLL_RXDS_DELAY_NUM_MSK    (0xfUL << SYS_CTL_DLL_RXDS_DELAY_NUM_POS) /*!< */
#define SYS_CTL_DLL_RXDS_DELAY_NUM        SYS_CTL_DLL_RXDS_DELAY_NUM_MSK
#define SYS_CTL_DLL_RXDS_DELAY_NUM_W(X)   ((X) << SYS_CTL_DLL_RXDS_DELAY_NUM_POS)
#define SYS_CTL_DLL_RXDS_SEL_POS          (4U)
#define SYS_CTL_DLL_RXDS_SEL_MSK          (0x1UL << SYS_CTL_DLL_RXDS_SEL_POS) /*!< */
#define SYS_CTL_DLL_RXDS_SEL              SYS_CTL_DLL_RXDS_SEL_MSK
#define SYS_CTL_DLL_RXDS_SEL_W(X)         ((X) << SYS_CTL_DLL_RXDS_SEL_POS)
#define SYS_CTL_DLL_1_RXDS_DELAY_NUM_POS  (8U)
#define SYS_CTL_DLL_1_RXDS_DELAY_NUM_MSK  (0xfUL << SYS_CTL_DLL_1_RXDS_DELAY_NUM_POS) /*!< */
#define SYS_CTL_DLL_1_RXDS_DELAY_NUM      SYS_CTL_DLL_1_RXDS_DELAY_NUM_MSK
#define SYS_CTL_DLL_1_RXDS_DELAY_NUM_W(X) ((X) << SYS_CTL_DLL_1_RXDS_DELAY_NUM_POS)
#define SYS_CTL_DLL_1_RXDS_SEL_POS        (12U)
#define SYS_CTL_DLL_1_RXDS_SEL_MSK        (0x1UL << SYS_CTL_DLL_1_RXDS_SEL_POS) /*!< */
#define SYS_CTL_DLL_1_RXDS_SEL            SYS_CTL_DLL_1_RXDS_SEL_MSK
#define SYS_CTL_DLL_1_RXDS_SEL_W(X)       ((X) << SYS_CTL_DLL_1_RXDS_SEL_POS)

//SDIO_CFG offsetaddress : 0x2E4
//SDIO_CFG RegResetValue : 0xNone
#define SYS_CTL_SDIO_CARD_WRITE_PRT_POS  (0U)
#define SYS_CTL_SDIO_CARD_WRITE_PRT_MSK  (0x1UL << SYS_CTL_SDIO_CARD_WRITE_PRT_POS) /*!< */
#define SYS_CTL_SDIO_CARD_WRITE_PRT      SYS_CTL_SDIO_CARD_WRITE_PRT_MSK
#define SYS_CTL_SDIO_CARD_WRITE_PRT_W(X) ((X) << SYS_CTL_SDIO_CARD_WRITE_PRT_POS)
#define SYS_CTL_SDIO_CARD_DETECT_N_POS   (1U)
#define SYS_CTL_SDIO_CARD_DETECT_N_MSK   (0x1UL << SYS_CTL_SDIO_CARD_DETECT_N_POS) /*!< */
#define SYS_CTL_SDIO_CARD_DETECT_N       SYS_CTL_SDIO_CARD_DETECT_N_MSK
#define SYS_CTL_SDIO_CARD_DETECT_N_W(X)  ((X) << SYS_CTL_SDIO_CARD_DETECT_N_POS)

//OTFAD_HADDR_MASK offsetaddress : 0x2F8
//OTFAD_HADDR_MASK RegResetValue : 0xNone
#define SYS_CTL_OTFAD_HADDR_MASK_POS  (0U)
#define SYS_CTL_OTFAD_HADDR_MASK_MSK  (0xffffffffUL << SYS_CTL_OTFAD_HADDR_MASK_POS) /*!< */
#define SYS_CTL_OTFAD_HADDR_MASK      SYS_CTL_OTFAD_HADDR_MASK_MSK
#define SYS_CTL_OTFAD_HADDR_MASK_W(X) ((X) << SYS_CTL_OTFAD_HADDR_MASK_POS)

//OTFAD_HADDR_MASK_1 offsetaddress : 0x2FC
//OTFAD_HADDR_MASK_1 RegResetValue : 0xNone
#define SYS_CTL_OTFAD_HADDR_MASK_1_POS  (0U)
#define SYS_CTL_OTFAD_HADDR_MASK_1_MSK  (0xffffffffUL << SYS_CTL_OTFAD_HADDR_MASK_1_POS) /*!< */
#define SYS_CTL_OTFAD_HADDR_MASK_1      SYS_CTL_OTFAD_HADDR_MASK_1_MSK
#define SYS_CTL_OTFAD_HADDR_MASK_1_W(X) ((X) << SYS_CTL_OTFAD_HADDR_MASK_1_POS)

//USB_RWREG_4 offsetaddress : 0x300
//USB_RWREG_4 RegResetValue : 0xNone
#define SYS_CTL_USB_RWREG_157_128_POS  (0U)
#define SYS_CTL_USB_RWREG_157_128_MSK  (0xffffffffUL << SYS_CTL_USB_RWREG_157_128_POS) /*!< */
#define SYS_CTL_USB_RWREG_157_128      SYS_CTL_USB_RWREG_157_128_MSK
#define SYS_CTL_USB_RWREG_157_128_W(X) ((X) << SYS_CTL_USB_RWREG_157_128_POS)

//USB_ROREG_10 offsetaddress : 0x304
//USB_ROREG_10 RegResetValue : 0xNone
#define SYS_CTL_USB_ROREG_333_320_POS  (0U)
#define SYS_CTL_USB_ROREG_333_320_MSK  (0xffffffffUL << SYS_CTL_USB_ROREG_333_320_POS) /*!< */
#define SYS_CTL_USB_ROREG_333_320      SYS_CTL_USB_ROREG_333_320_MSK
#define SYS_CTL_USB_ROREG_333_320_W(X) ((X) << SYS_CTL_USB_ROREG_333_320_POS)

//USB_RWREG_5 offsetaddress : 0x338
//USB_RWREG_5 RegResetValue : 0xNone
#define SYS_CTL_USB_RWREG_167_158_POS  (0U)
#define SYS_CTL_USB_RWREG_167_158_MSK  (0xffffffffUL << SYS_CTL_USB_RWREG_167_158_POS) /*!< */
#define SYS_CTL_USB_RWREG_167_158      SYS_CTL_USB_RWREG_167_158_MSK
#define SYS_CTL_USB_RWREG_167_158_W(X) ((X) << SYS_CTL_USB_RWREG_167_158_POS)

//SSI_CTL_REG offsetaddress : 0x340
//SSI_CTL_REG RegResetValue : 0xNone
#define SYS_CTL_SSI0_BYTE_EN_POS  (0U)
#define SYS_CTL_SSI0_BYTE_EN_MSK  (0x1UL << SYS_CTL_SSI0_BYTE_EN_POS) /*!< */
#define SYS_CTL_SSI0_BYTE_EN      SYS_CTL_SSI0_BYTE_EN_MSK
#define SYS_CTL_SSI0_BYTE_EN_W(X) ((X) << SYS_CTL_SSI0_BYTE_EN_POS)
#define SYS_CTL_SSI1_BYTE_EN_POS  (1U)
#define SYS_CTL_SSI1_BYTE_EN_MSK  (0x1UL << SYS_CTL_SSI1_BYTE_EN_POS) /*!< */
#define SYS_CTL_SSI1_BYTE_EN      SYS_CTL_SSI1_BYTE_EN_MSK
#define SYS_CTL_SSI1_BYTE_EN_W(X) ((X) << SYS_CTL_SSI1_BYTE_EN_POS)
#define SYS_CTL_RESERVED_POS      (2U)
#define SYS_CTL_RESERVED_MSK      (0x3fffffffUL << SYS_CTL_RESERVED_POS) /*!< */
#define SYS_CTL_RESERVED          SYS_CTL_RESERVED_MSK
#define SYS_CTL_RESERVED_W(X)     ((X) << SYS_CTL_RESERVED_POS)

//TEMP_TH_0 offsetaddress : 0x3a8
//TEMP_TH_0 RegResetValue: 0x Low temperature reduces the charging current threshold. When the temperature is less than or equal to the threshold, reduces the charging current
#define SYS_CTL_TEMP_LOW_STOP_TH_POS  (0U)
#define SYS_CTL_TEMP_LOW_STOP_TH_MSK  (0x3ffUL << SYS_CTL_TEMP_LOW_STOP_TH_POS) /*!< */
#define SYS_CTL_TEMP_LOW_STOP_TH      SYS_CTL_TEMP_LOW_STOP_TH_MSK
#define SYS_CTL_TEMP_LOW_STOP_TH_W(X) ((X) << SYS_CTL_TEMP_LOW_STOP_TH_POS)
#define SYS_CTL_TEMP_LOW_PROP_TH_POS  (10U)
#define SYS_CTL_TEMP_LOW_PROP_TH_MSK  (0x3ffUL << SYS_CTL_TEMP_LOW_PROP_TH_POS) /*!< */
#define SYS_CTL_TEMP_LOW_PROP_TH      SYS_CTL_TEMP_LOW_PROP_TH_MSK
#define SYS_CTL_TEMP_LOW_PROP_TH_W(X) ((X) << SYS_CTL_TEMP_LOW_PROP_TH_POS)
#define SYS_CTL_TEMP_NORMAL_TH_POS    (20U)
#define SYS_CTL_TEMP_NORMAL_TH_MSK    (0x3ffUL << SYS_CTL_TEMP_NORMAL_TH_POS) /*!< */
#define SYS_CTL_TEMP_NORMAL_TH        SYS_CTL_TEMP_NORMAL_TH_MSK
#define SYS_CTL_TEMP_NORMAL_TH_W(X)   ((X) << SYS_CTL_TEMP_NORMAL_TH_POS)

//TEMP_TH_1 offsetaddress : 0x3ac
//TEMP_TH_1 RegResetValue : 0xNone
#define SYS_CTL_TEMP_HIGH_PROP_TH_POS    (0U)
#define SYS_CTL_TEMP_HIGH_PROP_TH_MSK    (0x3ffUL << SYS_CTL_TEMP_HIGH_PROP_TH_POS) /*!< */
#define SYS_CTL_TEMP_HIGH_PROP_TH        SYS_CTL_TEMP_HIGH_PROP_TH_MSK
#define SYS_CTL_TEMP_HIGH_PROP_TH_W(X)   ((X) << SYS_CTL_TEMP_HIGH_PROP_TH_POS)
#define SYS_CTL_TEMP_TRIG_NUM_POS        (10U)
#define SYS_CTL_TEMP_TRIG_NUM_MSK        (0xfUL << SYS_CTL_TEMP_TRIG_NUM_POS) /*!< */
#define SYS_CTL_TEMP_TRIG_NUM            SYS_CTL_TEMP_TRIG_NUM_MSK
#define SYS_CTL_TEMP_TRIG_NUM_W(X)       ((X) << SYS_CTL_TEMP_TRIG_NUM_POS)
#define SYS_CTL_TEMP_TOTAL_SAMP_NUM_POS  (14U)
#define SYS_CTL_TEMP_TOTAL_SAMP_NUM_MSK  (0xfUL << SYS_CTL_TEMP_TOTAL_SAMP_NUM_POS) /*!< */
#define SYS_CTL_TEMP_TOTAL_SAMP_NUM      SYS_CTL_TEMP_TOTAL_SAMP_NUM_MSK
#define SYS_CTL_TEMP_TOTAL_SAMP_NUM_W(X) ((X) << SYS_CTL_TEMP_TOTAL_SAMP_NUM_POS)
#define SYS_CTL_CHG_STOP_POS             (20U)
#define SYS_CTL_CHG_STOP_MSK             (0x1UL << SYS_CTL_CHG_STOP_POS) /*!< */
#define SYS_CTL_CHG_STOP                 SYS_CTL_CHG_STOP_MSK
#define SYS_CTL_CHG_STOP_W(X)            ((X) << SYS_CTL_CHG_STOP_POS)
#define SYS_CTL_CHG_CV_SEL_POS           (21U)
#define SYS_CTL_CHG_CV_SEL_MSK           (0x7UL << SYS_CTL_CHG_CV_SEL_POS) /*!< */
#define SYS_CTL_CHG_CV_SEL               SYS_CTL_CHG_CV_SEL_MSK
#define SYS_CTL_CHG_CV_SEL_W(X)          ((X) << SYS_CTL_CHG_CV_SEL_POS)
#define SYS_CTL_CHG_CC_SEL_POS           (24U)
#define SYS_CTL_CHG_CC_SEL_MSK           (0x3fUL << SYS_CTL_CHG_CC_SEL_POS) /*!< */
#define SYS_CTL_CHG_CC_SEL               SYS_CTL_CHG_CC_SEL_MSK
#define SYS_CTL_CHG_CC_SEL_W(X)          ((X) << SYS_CTL_CHG_CC_SEL_POS)

//TEMP_CTRL offsetaddress : 0x3b0
//TEMP_CTRL RegResetValue : 0xNone
#define SYS_CTL_TEMP_HC_CTRL_EN_POS          (0U)
#define SYS_CTL_TEMP_HC_CTRL_EN_MSK          (0x1UL << SYS_CTL_TEMP_HC_CTRL_EN_POS) /*!< */
#define SYS_CTL_TEMP_HC_CTRL_EN              SYS_CTL_TEMP_HC_CTRL_EN_MSK
#define SYS_CTL_TEMP_HC_CTRL_EN_W(X)         ((X) << SYS_CTL_TEMP_HC_CTRL_EN_POS)
#define SYS_CTL_HC_CHG_CV_SEL_HIGH_PROP_POS  (1U)
#define SYS_CTL_HC_CHG_CV_SEL_HIGH_PROP_MSK  (0x7UL << SYS_CTL_HC_CHG_CV_SEL_HIGH_PROP_POS) /*!< */
#define SYS_CTL_HC_CHG_CV_SEL_HIGH_PROP      SYS_CTL_HC_CHG_CV_SEL_HIGH_PROP_MSK
#define SYS_CTL_HC_CHG_CV_SEL_HIGH_PROP_W(X) ((X) << SYS_CTL_HC_CHG_CV_SEL_HIGH_PROP_POS)
#define SYS_CTL_HC_CHG_CC_SEL_HIGH_PROP_POS  (4U)
#define SYS_CTL_HC_CHG_CC_SEL_HIGH_PROP_MSK  (0x3fUL << SYS_CTL_HC_CHG_CC_SEL_HIGH_PROP_POS) /*!< */
#define SYS_CTL_HC_CHG_CC_SEL_HIGH_PROP      SYS_CTL_HC_CHG_CC_SEL_HIGH_PROP_MSK
#define SYS_CTL_HC_CHG_CC_SEL_HIGH_PROP_W(X) ((X) << SYS_CTL_HC_CHG_CC_SEL_HIGH_PROP_POS)
#define SYS_CTL_HC_CHG_CV_SEL_NORM_POS       (10U)
#define SYS_CTL_HC_CHG_CV_SEL_NORM_MSK       (0x7UL << SYS_CTL_HC_CHG_CV_SEL_NORM_POS) /*!< */
#define SYS_CTL_HC_CHG_CV_SEL_NORM           SYS_CTL_HC_CHG_CV_SEL_NORM_MSK
#define SYS_CTL_HC_CHG_CV_SEL_NORM_W(X)      ((X) << SYS_CTL_HC_CHG_CV_SEL_NORM_POS)
#define SYS_CTL_HC_CHG_CC_SEL_NORM_POS       (13U)
#define SYS_CTL_HC_CHG_CC_SEL_NORM_MSK       (0x3fUL << SYS_CTL_HC_CHG_CC_SEL_NORM_POS) /*!< */
#define SYS_CTL_HC_CHG_CC_SEL_NORM           SYS_CTL_HC_CHG_CC_SEL_NORM_MSK
#define SYS_CTL_HC_CHG_CC_SEL_NORM_W(X)      ((X) << SYS_CTL_HC_CHG_CC_SEL_NORM_POS)
#define SYS_CTL_HC_CHG_CV_SEL_LOW_PROP_POS   (19U)
#define SYS_CTL_HC_CHG_CV_SEL_LOW_PROP_MSK   (0x7UL << SYS_CTL_HC_CHG_CV_SEL_LOW_PROP_POS) /*!< */
#define SYS_CTL_HC_CHG_CV_SEL_LOW_PROP       SYS_CTL_HC_CHG_CV_SEL_LOW_PROP_MSK
#define SYS_CTL_HC_CHG_CV_SEL_LOW_PROP_W(X)  ((X) << SYS_CTL_HC_CHG_CV_SEL_LOW_PROP_POS)
#define SYS_CTL_HC_CHG_CC_SEL_LOW_PROP_POS   (22U)
#define SYS_CTL_HC_CHG_CC_SEL_LOW_PROP_MSK   (0x3fUL << SYS_CTL_HC_CHG_CC_SEL_LOW_PROP_POS) /*!< */
#define SYS_CTL_HC_CHG_CC_SEL_LOW_PROP       SYS_CTL_HC_CHG_CC_SEL_LOW_PROP_MSK
#define SYS_CTL_HC_CHG_CC_SEL_LOW_PROP_W(X)  ((X) << SYS_CTL_HC_CHG_CC_SEL_LOW_PROP_POS)
#define SYS_CTL_TEMP_MON_EN_POS              (30U)
#define SYS_CTL_TEMP_MON_EN_MSK              (0x1UL << SYS_CTL_TEMP_MON_EN_POS) /*!< */
#define SYS_CTL_TEMP_MON_EN                  SYS_CTL_TEMP_MON_EN_MSK
#define SYS_CTL_TEMP_MON_EN_W(X)             ((X) << SYS_CTL_TEMP_MON_EN_POS)

//TEST_CFG1 offsetaddress : 0x3b4
//TEST_CFG1 RegResetValue : 0xNone
#define SYS_CTL_TEST_PIN_BITMUX_31_0_POS  (0U)
#define SYS_CTL_TEST_PIN_BITMUX_31_0_MSK  (0xffffffffUL << SYS_CTL_TEST_PIN_BITMUX_31_0_POS) /*!< */
#define SYS_CTL_TEST_PIN_BITMUX_31_0      SYS_CTL_TEST_PIN_BITMUX_31_0_MSK
#define SYS_CTL_TEST_PIN_BITMUX_31_0_W(X) ((X) << SYS_CTL_TEST_PIN_BITMUX_31_0_POS)

//TEST_CFG2 offsetaddress : 0x3b8
//TEST_CFG2 RegResetValue : 0xNone
#define SYS_CTL_TEST_PIN_BITMUX_63_32_POS  (0U)
#define SYS_CTL_TEST_PIN_BITMUX_63_32_MSK  (0xffffffffUL << SYS_CTL_TEST_PIN_BITMUX_63_32_POS) /*!< */
#define SYS_CTL_TEST_PIN_BITMUX_63_32      SYS_CTL_TEST_PIN_BITMUX_63_32_MSK
#define SYS_CTL_TEST_PIN_BITMUX_63_32_W(X) ((X) << SYS_CTL_TEST_PIN_BITMUX_63_32_POS)

//DLL0_CONFIG offsetaddress : 0x480
//DLL0_CONFIG RegResetValue : 0xNone
#define SYS_CTL_PHY_PHASE_DELAY_RX_POS  (0U)
#define SYS_CTL_PHY_PHASE_DELAY_RX_MSK  (0x7fUL << SYS_CTL_PHY_PHASE_DELAY_RX_POS) /*!< */
#define SYS_CTL_PHY_PHASE_DELAY_RX      SYS_CTL_PHY_PHASE_DELAY_RX_MSK
#define SYS_CTL_PHY_PHASE_DELAY_RX_W(X) ((X) << SYS_CTL_PHY_PHASE_DELAY_RX_POS)
#define SYS_CTL_PHY_PHASE_DELAY_TX_POS  (16U)
#define SYS_CTL_PHY_PHASE_DELAY_TX_MSK  (0x7fUL << SYS_CTL_PHY_PHASE_DELAY_TX_POS) /*!< */
#define SYS_CTL_PHY_PHASE_DELAY_TX      SYS_CTL_PHY_PHASE_DELAY_TX_MSK
#define SYS_CTL_PHY_PHASE_DELAY_TX_W(X) ((X) << SYS_CTL_PHY_PHASE_DELAY_TX_POS)
#define SYS_CTL_PHY_RX_DLL_BYPASS_POS   (29U)
#define SYS_CTL_PHY_RX_DLL_BYPASS_MSK   (0x1UL << SYS_CTL_PHY_RX_DLL_BYPASS_POS) /*!< */
#define SYS_CTL_PHY_RX_DLL_BYPASS       SYS_CTL_PHY_RX_DLL_BYPASS_MSK
#define SYS_CTL_PHY_RX_DLL_BYPASS_W(X)  ((X) << SYS_CTL_PHY_RX_DLL_BYPASS_POS)
#define SYS_CTL_PHY_RESET_DLL_POS       (30U)
#define SYS_CTL_PHY_RESET_DLL_MSK       (0x1UL << SYS_CTL_PHY_RESET_DLL_POS) /*!< */
#define SYS_CTL_PHY_RESET_DLL           SYS_CTL_PHY_RESET_DLL_MSK
#define SYS_CTL_PHY_RESET_DLL_W(X)      ((X) << SYS_CTL_PHY_RESET_DLL_POS)
#define SYS_CTL_PHY_RESYNC_DLL_POS      (31U)
#define SYS_CTL_PHY_RESYNC_DLL_MSK      (0x1UL << SYS_CTL_PHY_RESYNC_DLL_POS) /*!< */
#define SYS_CTL_PHY_RESYNC_DLL          SYS_CTL_PHY_RESYNC_DLL_MSK
#define SYS_CTL_PHY_RESYNC_DLL_W(X)     ((X) << SYS_CTL_PHY_RESYNC_DLL_POS)

//DLL0_MASTER offsetaddress : 0x484
//DLL0_MASTER RegResetValue : 0xNone
#define SYS_CTL_PHY_DLL_START_POINT_POS  (0U)
#define SYS_CTL_PHY_DLL_START_POINT_MSK  (0x7fUL << SYS_CTL_PHY_DLL_START_POINT_POS) /*!< */
#define SYS_CTL_PHY_DLL_START_POINT      SYS_CTL_PHY_DLL_START_POINT_MSK
#define SYS_CTL_PHY_DLL_START_POINT_W(X) ((X) << SYS_CTL_PHY_DLL_START_POINT_POS)
#define SYS_CTL_PHY_DLL_LOCK_NUM_POS     (16U)
#define SYS_CTL_PHY_DLL_LOCK_NUM_MSK     (0x7UL << SYS_CTL_PHY_DLL_LOCK_NUM_POS) /*!< */
#define SYS_CTL_PHY_DLL_LOCK_NUM         SYS_CTL_PHY_DLL_LOCK_NUM_MSK
#define SYS_CTL_PHY_DLL_LOCK_NUM_W(X)    ((X) << SYS_CTL_PHY_DLL_LOCK_NUM_POS)
#define SYS_CTL_PHY_PHASE_DET_SEL_POS    (20U)
#define SYS_CTL_PHY_PHASE_DET_SEL_MSK    (0x7UL << SYS_CTL_PHY_PHASE_DET_SEL_POS) /*!< */
#define SYS_CTL_PHY_PHASE_DET_SEL        SYS_CTL_PHY_PHASE_DET_SEL_MSK
#define SYS_CTL_PHY_PHASE_DET_SEL_W(X)   ((X) << SYS_CTL_PHY_PHASE_DET_SEL_POS)
#define SYS_CTL_PHY_DLL_BYPASS_MODE_POS  (23U)
#define SYS_CTL_PHY_DLL_BYPASS_MODE_MSK  (0x1UL << SYS_CTL_PHY_DLL_BYPASS_MODE_POS) /*!< */
#define SYS_CTL_PHY_DLL_BYPASS_MODE      SYS_CTL_PHY_DLL_BYPASS_MODE_MSK
#define SYS_CTL_PHY_DLL_BYPASS_MODE_W(X) ((X) << SYS_CTL_PHY_DLL_BYPASS_MODE_POS)
#define SYS_CTL_PHY_HALF_CLK_MODE_POS    (24U)
#define SYS_CTL_PHY_HALF_CLK_MODE_MSK    (0x1UL << SYS_CTL_PHY_HALF_CLK_MODE_POS) /*!< */
#define SYS_CTL_PHY_HALF_CLK_MODE        SYS_CTL_PHY_HALF_CLK_MODE_MSK
#define SYS_CTL_PHY_HALF_CLK_MODE_W(X)   ((X) << SYS_CTL_PHY_HALF_CLK_MODE_POS)

//DLL0_OBS_L offsetaddress : 0x488
//DLL0_OBS_L RegResetValue : 0xNone
#define SYS_CTL_PHY_PENDING_REG_SYNC_31_0_POS  (0U)
#define SYS_CTL_PHY_PENDING_REG_SYNC_31_0_MSK  (0xffffffffUL << SYS_CTL_PHY_PENDING_REG_SYNC_31_0_POS) /*!< */
#define SYS_CTL_PHY_PENDING_REG_SYNC_31_0      SYS_CTL_PHY_PENDING_REG_SYNC_31_0_MSK
#define SYS_CTL_PHY_PENDING_REG_SYNC_31_0_W(X) ((X) << SYS_CTL_PHY_PENDING_REG_SYNC_31_0_POS)

//DLL0_OBS_H offsetaddress : 0x48C
//DLL0_OBS_H RegResetValue : 0xNone
#define SYS_CTL_PHY_PENDING_REG_SYNC_63_32_POS  (0U)
#define SYS_CTL_PHY_PENDING_REG_SYNC_63_32_MSK  (0xffffffffUL << SYS_CTL_PHY_PENDING_REG_SYNC_63_32_POS) /*!< */
#define SYS_CTL_PHY_PENDING_REG_SYNC_63_32      SYS_CTL_PHY_PENDING_REG_SYNC_63_32_MSK
#define SYS_CTL_PHY_PENDING_REG_SYNC_63_32_W(X) ((X) << SYS_CTL_PHY_PENDING_REG_SYNC_63_32_POS)

//DLL1_CONFIG offsetaddress : 0x4C0
//DLL1_CONFIG RegResetValue : 0xNone
#define SYS_CTL_PHY_PHASE_DELAY_RX_DLL1_CONFIG_POS  (0U)
#define SYS_CTL_PHY_PHASE_DELAY_RX_DLL1_CONFIG_MSK  (0x7fUL << SYS_CTL_PHY_PHASE_DELAY_RX_DLL1_CONFIG_POS) /*!< */
#define SYS_CTL_PHY_PHASE_DELAY_RX_DLL1_CONFIG      SYS_CTL_PHY_PHASE_DELAY_RX_DLL1_CONFIG_MSK
#define SYS_CTL_PHY_PHASE_DELAY_RX_DLL1_CONFIG_W(X) ((X) << SYS_CTL_PHY_PHASE_DELAY_RX_DLL1_CONFIG_POS)
#define SYS_CTL_PHY_PHASE_DELAY_TX_DLL1_CONFIG_POS  (16U)
#define SYS_CTL_PHY_PHASE_DELAY_TX_DLL1_CONFIG_MSK  (0x7fUL << SYS_CTL_PHY_PHASE_DELAY_TX_DLL1_CONFIG_POS) /*!< */
#define SYS_CTL_PHY_PHASE_DELAY_TX_DLL1_CONFIG      SYS_CTL_PHY_PHASE_DELAY_TX_DLL1_CONFIG_MSK
#define SYS_CTL_PHY_PHASE_DELAY_TX_DLL1_CONFIG_W(X) ((X) << SYS_CTL_PHY_PHASE_DELAY_TX_DLL1_CONFIG_POS)
#define SYS_CTL_PHY_RX_DLL_BYPASS_DLL1_CONFIG_POS   (29U)
#define SYS_CTL_PHY_RX_DLL_BYPASS_DLL1_CONFIG_MSK   (0x1UL << SYS_CTL_PHY_RX_DLL_BYPASS_DLL1_CONFIG_POS) /*!< */
#define SYS_CTL_PHY_RX_DLL_BYPASS_DLL1_CONFIG       SYS_CTL_PHY_RX_DLL_BYPASS_DLL1_CONFIG_MSK
#define SYS_CTL_PHY_RX_DLL_BYPASS_DLL1_CONFIG_W(X)  ((X) << SYS_CTL_PHY_RX_DLL_BYPASS_DLL1_CONFIG_POS)
#define SYS_CTL_PHY_RESET_DLL_DLL1_CONFIG_POS       (30U)
#define SYS_CTL_PHY_RESET_DLL_DLL1_CONFIG_MSK       (0x1UL << SYS_CTL_PHY_RESET_DLL_DLL1_CONFIG_POS) /*!< */
#define SYS_CTL_PHY_RESET_DLL_DLL1_CONFIG           SYS_CTL_PHY_RESET_DLL_DLL1_CONFIG_MSK
#define SYS_CTL_PHY_RESET_DLL_DLL1_CONFIG_W(X)      ((X) << SYS_CTL_PHY_RESET_DLL_DLL1_CONFIG_POS)
#define SYS_CTL_PHY_RESYNC_DLL_DLL1_CONFIG_POS      (31U)
#define SYS_CTL_PHY_RESYNC_DLL_DLL1_CONFIG_MSK      (0x1UL << SYS_CTL_PHY_RESYNC_DLL_DLL1_CONFIG_POS) /*!< */
#define SYS_CTL_PHY_RESYNC_DLL_DLL1_CONFIG          SYS_CTL_PHY_RESYNC_DLL_DLL1_CONFIG_MSK
#define SYS_CTL_PHY_RESYNC_DLL_DLL1_CONFIG_W(X)     ((X) << SYS_CTL_PHY_RESYNC_DLL_DLL1_CONFIG_POS)

//DLL1_MASTER offsetaddress : 0x4C4
//DLL1_MASTER RegResetValue : 0xNone
#define SYS_CTL_PHY_DLL_START_POINT_DLL1_MASTER_POS  (0U)
#define SYS_CTL_PHY_DLL_START_POINT_DLL1_MASTER_MSK  (0x7fUL << SYS_CTL_PHY_DLL_START_POINT_DLL1_MASTER_POS) /*!< */
#define SYS_CTL_PHY_DLL_START_POINT_DLL1_MASTER      SYS_CTL_PHY_DLL_START_POINT_DLL1_MASTER_MSK
#define SYS_CTL_PHY_DLL_START_POINT_DLL1_MASTER_W(X) ((X) << SYS_CTL_PHY_DLL_START_POINT_DLL1_MASTER_POS)
#define SYS_CTL_PHY_DLL_LOCK_NUM_DLL1_MASTER_POS     (16U)
#define SYS_CTL_PHY_DLL_LOCK_NUM_DLL1_MASTER_MSK     (0x7UL << SYS_CTL_PHY_DLL_LOCK_NUM_DLL1_MASTER_POS) /*!< */
#define SYS_CTL_PHY_DLL_LOCK_NUM_DLL1_MASTER         SYS_CTL_PHY_DLL_LOCK_NUM_DLL1_MASTER_MSK
#define SYS_CTL_PHY_DLL_LOCK_NUM_DLL1_MASTER_W(X)    ((X) << SYS_CTL_PHY_DLL_LOCK_NUM_DLL1_MASTER_POS)
#define SYS_CTL_PHY_PHASE_DET_SEL_DLL1_MASTER_POS    (20U)
#define SYS_CTL_PHY_PHASE_DET_SEL_DLL1_MASTER_MSK    (0x7UL << SYS_CTL_PHY_PHASE_DET_SEL_DLL1_MASTER_POS) /*!< */
#define SYS_CTL_PHY_PHASE_DET_SEL_DLL1_MASTER        SYS_CTL_PHY_PHASE_DET_SEL_DLL1_MASTER_MSK
#define SYS_CTL_PHY_PHASE_DET_SEL_DLL1_MASTER_W(X)   ((X) << SYS_CTL_PHY_PHASE_DET_SEL_DLL1_MASTER_POS)
#define SYS_CTL_PHY_DLL_BYPASS_MODE_DLL1_MASTER_POS  (23U)
#define SYS_CTL_PHY_DLL_BYPASS_MODE_DLL1_MASTER_MSK  (0x1UL << SYS_CTL_PHY_DLL_BYPASS_MODE_DLL1_MASTER_POS) /*!< */
#define SYS_CTL_PHY_DLL_BYPASS_MODE_DLL1_MASTER      SYS_CTL_PHY_DLL_BYPASS_MODE_DLL1_MASTER_MSK
#define SYS_CTL_PHY_DLL_BYPASS_MODE_DLL1_MASTER_W(X) ((X) << SYS_CTL_PHY_DLL_BYPASS_MODE_DLL1_MASTER_POS)
#define SYS_CTL_PHY_HALF_CLK_MODE_DLL1_MASTER_POS    (24U)
#define SYS_CTL_PHY_HALF_CLK_MODE_DLL1_MASTER_MSK    (0x1UL << SYS_CTL_PHY_HALF_CLK_MODE_DLL1_MASTER_POS) /*!< */
#define SYS_CTL_PHY_HALF_CLK_MODE_DLL1_MASTER        SYS_CTL_PHY_HALF_CLK_MODE_DLL1_MASTER_MSK
#define SYS_CTL_PHY_HALF_CLK_MODE_DLL1_MASTER_W(X)   ((X) << SYS_CTL_PHY_HALF_CLK_MODE_DLL1_MASTER_POS)

//DLL1_OBS_L offsetaddress : 0x4C8
//DLL1_OBS_L RegResetValue : 0xNone
#define SYS_CTL_PHY_PENDING_REG_SYNC_31_0_DLL1_OBS_L_POS  (0U)
#define SYS_CTL_PHY_PENDING_REG_SYNC_31_0_DLL1_OBS_L_MSK  (0xffffffffUL << SYS_CTL_PHY_PENDING_REG_SYNC_31_0_DLL1_OBS_L_POS) /*!< */
#define SYS_CTL_PHY_PENDING_REG_SYNC_31_0_DLL1_OBS_L      SYS_CTL_PHY_PENDING_REG_SYNC_31_0_DLL1_OBS_L_MSK
#define SYS_CTL_PHY_PENDING_REG_SYNC_31_0_DLL1_OBS_L_W(X) ((X) << SYS_CTL_PHY_PENDING_REG_SYNC_31_0_DLL1_OBS_L_POS)

//DLL1_OBS_H offsetaddress : 0x4CC
//DLL1_OBS_H RegResetValue : 0xNone
#define SYS_CTL_PHY_PENDING_REG_SYNC_63_32_DLL1_OBS_H_POS  (0U)
#define SYS_CTL_PHY_PENDING_REG_SYNC_63_32_DLL1_OBS_H_MSK  (0xffffffffUL << SYS_CTL_PHY_PENDING_REG_SYNC_63_32_DLL1_OBS_H_POS) /*!< */
#define SYS_CTL_PHY_PENDING_REG_SYNC_63_32_DLL1_OBS_H      SYS_CTL_PHY_PENDING_REG_SYNC_63_32_DLL1_OBS_H_MSK
#define SYS_CTL_PHY_PENDING_REG_SYNC_63_32_DLL1_OBS_H_W(X) ((X) << SYS_CTL_PHY_PENDING_REG_SYNC_63_32_DLL1_OBS_H_POS)

typedef struct {
    volatile uint32_t rev_0[(0x21C - 0x00) / 4];
    volatile uint32_t PERI_CFG_REG; //offsetaddress : 0x21C
    volatile uint32_t SSI_CFG_REG;  //offsetaddress : 0x220
    volatile uint32_t rev_1[(0x23c - 0x220) / 4 - 1];
    volatile uint32_t OSR_CFG_REG; //offsetaddress : 0x23c
    volatile uint32_t rev_2[(0x254 - 0x23c) / 4 - 1];
    volatile uint32_t PDM_CFG;  //offsetaddress : 0x254
    volatile uint32_t TEST_CFG; //offsetaddress : 0x258
    volatile uint32_t rev_3[(0x260 - 0x258) / 4 - 1];
    volatile uint32_t GP_ADC_SYS_CTL; //offsetaddress : 0x260
    volatile uint32_t BOOT_STATUS;    //offsetaddress : 0x264
    volatile uint32_t USB_ROREG_0;    //offsetaddress : 0x268
    volatile uint32_t USB_ROREG_1;    //offsetaddress : 0x26C
    volatile uint32_t USB_ROREG_2;    //offsetaddress : 0x270
    volatile uint32_t USB_ROREG_3;    //offsetaddress : 0x274
    volatile uint32_t USB_ROREG_4;    //offsetaddress : 0x278
    volatile uint32_t USB_ROREG_5;    //offsetaddress : 0x27C
    volatile uint32_t USB_ROREG_6;    //offsetaddress : 0x280
    volatile uint32_t USB_ROREG_7;    //offsetaddress : 0x284
    volatile uint32_t USB_ROREG_8;    //offsetaddress : 0x288
    volatile uint32_t USB_ROREG_9;    //offsetaddress : 0x28C
    volatile uint32_t USB_RWREG_0;    //offsetaddress : 0x290
    volatile uint32_t USB_RWREG_1;    //offsetaddress : 0x294
    volatile uint32_t USB_RWREG_2;    //offsetaddress : 0x298
    volatile uint32_t USB_RWREG_3;    //offsetaddress : 0x29C
    volatile uint32_t rev_4[(0x2D0 - 0x29C) / 4 - 1];
    volatile uint32_t AUDIO_FUNC_DMA_SEL; //offsetaddress : 0x2D0
    volatile uint32_t rev_5[(0x2E0 - 0x2D0) / 4 - 1];
    volatile uint32_t DLL_RXDS; //offsetaddress : 0x2E0
    volatile uint32_t SDIO_CFG; //offsetaddress : 0x2E4
    volatile uint32_t rev_6[(0x2F8 - 0x2E4) / 4 - 1];
    volatile uint32_t OTFAD_HADDR_MASK;   //offsetaddress : 0x2F8
    volatile uint32_t OTFAD_HADDR_MASK_1; //offsetaddress : 0x2FC
    volatile uint32_t USB_RWREG_4;        //offsetaddress : 0x300
    volatile uint32_t USB_ROREG_10;       //offsetaddress : 0x304
    volatile uint32_t rev_7[(0x338 - 0x304) / 4 - 1];
    volatile uint32_t USB_RWREG_5; //offsetaddress : 0x338
    volatile uint32_t rev_8[(0x340 - 0x338) / 4 - 1];
    volatile uint32_t SSI_CTL_REG; //offsetaddress : 0x340
    volatile uint32_t rev_9[(0x3a8 - 0x340) / 4 - 1];
    volatile uint32_t TEMP_TH_0; //offsetaddress : 0x3a8
    volatile uint32_t TEMP_TH_1; //offsetaddress : 0x3ac
    volatile uint32_t TEMP_CTRL; //offsetaddress : 0x3b0
    volatile uint32_t TEST_CFG1; //offsetaddress : 0x3b4
    volatile uint32_t TEST_CFG2; //offsetaddress : 0x3b8
    volatile uint32_t rev_10[(0x480 - 0x3b8) / 4 - 1];
    volatile uint32_t DLL0_CONFIG; //offsetaddress : 0x480
    volatile uint32_t DLL0_MASTER; //offsetaddress : 0x484
    volatile uint32_t DLL0_OBS_L;  //offsetaddress : 0x488
    volatile uint32_t DLL0_OBS_H;  //offsetaddress : 0x48C
    volatile uint32_t rev_11[(0x4C0 - 0x48C) / 4 - 1];
    volatile uint32_t DLL1_CONFIG; //offsetaddress : 0x4C0
    volatile uint32_t DLL1_MASTER; //offsetaddress : 0x4C4
    volatile uint32_t DLL1_OBS_L;  //offsetaddress : 0x4C8
    volatile uint32_t DLL1_OBS_H;  //offsetaddress : 0x4CC
} sys_ctl_reg_t;
#ifdef __cplusplus
}
#endif
#endif